species_table <-
function(x){
  
  
  structure(list(name = c("Rhogeessa tumida", "Rhogeessa minutilla", 
                          "Rhogeessa genowaysi", "Rhogeessa parvula", "Rhogeessa alleni", 
                          "Rhogeessa mira", "Rhogeessa gracilis", "Scotomanes ornatus", 
                          "Philetor brachypterus", "Chalinolobus dwyeri", "Chalinolobus gouldii", 
                          "Chalinolobus nigrogriseus", "Chalinolobus tuberculatus", "Chalinolobus picatus", 
                          "Chalinolobus morio", "Histiotus montanus", "Histiotus macrotus", 
                          "Histiotus velatus", "Histiotus alienus", "Laephotis namibensis", 
                          "Laephotis wintoni", "Laephotis botswanae", "Laephotis angolensis", 
                          "Nycticeius humeralis", "Pharotis imogene", "Murina aenea", "Murina florium", 
                          "Murina puta", "Murina suilla", "Murina ussuriensis", "Murina aurata", 
                          "Murina fusca", "Murina rozendaali", "Murina tenebrosa", "Murina cyclotis", 
                          "Murina leucogaster", "Murina tubinaris", "Scotoecus pallidus", 
                          "Scotoecus hirundo", "Scotoecus albofuscus", "Antrozous pallidus", 
                          "Lasionycteris noctivagans", "Tylonycteris pachypus", "Tylonycteris robustula", 
                          "Eptesicus bottae", "Eptesicus guadeloupensis", "Eptesicus fuscus", 
                          "Eptesicus innoxius", "Eptesicus serotinus", "Eptesicus tatei", 
                          "Eptesicus furinalis", "Eptesicus hottentotus", "Eptesicus platyops", 
                          "Eptesicus brasiliensis", "Eptesicus diminutus", "Eptesicus floweri", 
                          "Eptesicus pachyotis", "Harpiocephalus harpia", "Otonycteris hemprichii", 
                          "Myotis riparius", "Myotis velifer", "Myotis horsfieldii", "Myotis nattereri", 
                          "Myotis levis", "Myotis vivesi", "Myotis annectans", "Myotis elegans", 
                          "Myotis ridleyi", "Myotis thysanodes", "Myotis hasseltii", "Myotis scotti", 
                          "Myotis chinensis", "Myotis tricolor", "Myotis lucifugus", "Myotis altarium", 
                          "Myotis dominicensis", "Myotis martiniquensis", "Myotis volans", 
                          "Myotis evotis", "Myotis blythii", "Myotis goudotii", "Myotis myotis", 
                          "Myotis schaubi", "Myotis sodalis", "Myotis chiloensis", "Myotis keaysi", 
                          "Myotis fortidens", "Myotis oxyotus", "Myotis stalkeri", "Myotis albescens", 
                          "Myotis californicus", "Myotis pruinosus", "Myotis bechsteinii", 
                          "Myotis frater", "Myotis muricola", "Myotis capaccinii", "Myotis ikonnikovi", 
                          "Myotis grisescens", "Myotis oreias", "Myotis simus", "Myotis keenii", 
                          "Myotis septentrionalis", "Myotis auriculus", "Myotis daubentonii", 
                          "Myotis macrotarsus", "Myotis planiceps", "Myotis australis", 
                          "Myotis formosus", "Myotis morrisi", "Myotis ruber", "Myotis insularum", 
                          "Myotis nigricans", "Myotis siligorensis", "Myotis adversus", 
                          "Myotis austroriparius", "Myotis dasycneme", "Myotis macrodactylus", 
                          "Myotis pequinius", "Myotis leibii", "Myotis ciliolabrum", "Myotis atacamensis", 
                          "Myotis findleyi", "Myotis montivagus", "Myotis rosseti", "Myotis yumanensis", 
                          "Myotis bombinus", "Myotis nesopolus", "Myotis sicarius", "Myotis cobanensis", 
                          "Myotis longipes", "Myotis peninsularis", "Myotis welwitschii", 
                          "Myotis emarginatus", "Corynorhinus townsendii", "Corynorhinus mexicanus", 
                          "Corynorhinus rafinesquii", "Miniopterus robustior", "Miniopterus magnater", 
                          "Miniopterus fraterculus", "Miniopterus tristis", "Miniopterus pusillus", 
                          "Miniopterus inflatus", "Miniopterus australis", "Miniopterus minor", 
                          "Miniopterus fuscus", "Glischropus javanus", "Glischropus tylopus", 
                          "Nyctophilus walkeri", "Nyctophilus gouldi", "Nyctophilus microtis", 
                          "Nyctophilus geoffroyi", "Nyctophilus heran", "Nyctophilus microdon", 
                          "Nyctophilus arnhemensis", "Idionycteris phyllotis", "Mimetillus moloneyi", 
                          "Hesperoptenus tomesi", "Hesperoptenus gaskelli", "Hesperoptenus tickelli", 
                          "Hesperoptenus doriae", "Hesperoptenus blanfordi", "Kerivoula whiteheadi", 
                          "Kerivoula agnella", "Kerivoula cuprosa", "Kerivoula flora", 
                          "Kerivoula minuta", "Kerivoula papillosa", "Kerivoula pellucida", 
                          "Kerivoula picta", "Kerivoula argentata", "Kerivoula eriophora", 
                          "Kerivoula hardwickii", "Kerivoula muscina", "Kerivoula phalaena", 
                          "Kerivoula smithii", "Kerivoula africana", "Kerivoula intermedia", 
                          "Kerivoula lanosa", "Kerivoula myrella", "Eudiscopus denticulus", 
                          "Vespertilio murinus", "Ia io", "Euderma maculatum", "Barbastella leucomelas", 
                          "Barbastella barbastellus", "Aselliscus stoliczkanus", "Aselliscus tricuspidatus", 
                          "Asellia patrizii", "Asellia tridens", "Anthops ornatus", "Rhinolophus silvestris", 
                          "Rhinolophus celebensis", "Rhinolophus hipposideros", "Rhinolophus osgoodi", 
                          "Rhinolophus subrufus", "Rhinolophus creaghi", "Rhinolophus lepidus", 
                          "Rhinolophus rex", "Rhinolophus euryale", "Rhinolophus megaphyllus", 
                          "Rhinolophus shameli", "Rhinolophus subbadius", "Rhinolophus acuminatus", 
                          "Rhinolophus cornutus", "Rhinolophus landeri", "Rhinolophus yunanensis", 
                          "Rhinolophus alcyone", "Rhinolophus eloquens", "Rhinolophus marshalli", 
                          "Rhinolophus capensis", "Rhinolophus guineensis", "Rhinolophus nereis", 
                          "Rhinolophus stheno", "Rhinolophus cognatus", "Rhinolophus keyensis", 
                          "Rhinolophus pusillus", "Rhinolophus virgo", "Rhinolophus affinis", 
                          "Rhinolophus malayanus", "Rhinolophus sedulus", "Rhinolophus canuti", 
                          "Rhinolophus fumigatus", "Rhinolophus monoceros", "Rhinolophus coelophyllus", 
                          "Rhinolophus inops", "Rhinolophus philippinensis", "Rhinolophus trifoliatus", 
                          "Rhinolophus denti", "Rhinolophus macrotis", "Rhinolophus rufus", 
                          "Rhinolophus borneensis", "Rhinolophus ferrumequinum", "Rhinolophus mitratus", 
                          "Rhinolophus simulator", "Rhinolophus pearsonii", "Rhinolophus thomasi", 
                          "Rhinolophus adami", "Rhinolophus deckenii", "Rhinolophus maclaudi", 
                          "Rhinolophus rouxii", "Rhinolophus blasii", "Rhinolophus mehelyi", 
                          "Rhinolophus clivosus", "Rhinolophus swinnyi", "Rhinolophus darlingi", 
                          "Rhinolophus luctus", "Rhinolophus robinsoni", "Rhinolophus arcuatus", 
                          "Rhinolophus euryotis", "Cloeotis percivali", "Triaenops persicus", 
                          "Rhinonicteris aurantia", "Natalus tumidirostris", "Natalus stramineus", 
                          "Mormoops megalophylla", "Furipterus horrens", "Amorphochilus schnablii", 
                          "Thyroptera tricolor", "Thyroptera discifera", "Dyacopterus spadiceus", 
                          "Scotonycteris zenkeri", "Thoopterus nigrescens", "Epomophorus angolensis", 
                          "Epomophorus wahlbergi", "Epomophorus grandis", "Epomophorus gambianus", 
                          "Epomophorus labiatus", "Melonycteris melanops", "Megaloglossus woermanni", 
                          "Epomops franqueti", "Epomops buettikoferi", "Dobsonia praedatrix", 
                          "Dobsonia moluccensis", "Dobsonia exoleta", "Dobsonia minor", 
                          "Dobsonia chapmani", "Dobsonia viridis", "Dobsonia pannietensis", 
                          "Dobsonia inermis", "Dobsonia emersa", "Dobsonia beauforti", 
                          "Cynopterus titthaecheilus", "Cynopterus sphinx", "Cynopterus brachyotis", 
                          "Cynopterus nusatenggara", "Harpyionycteris whiteheadi", "Harpyionycteris celebensis", 
                          "Boneia bidens", "Chironax melanocephalus", "Ptenochirus jagorii", 
                          "Ptenochirus minor", "Eidolon dupreanum", "Eidolon helvum", "Casinycteris argynnis", 
                          "Sphaerias blanfordi", "Megaerops kusnotoi", "Megaerops niphanae", 
                          "Megaerops ecaudatus", "Otopteropus cartilagonodus", "Styloctenium wallacei", 
                          "Penthetor lucasii", "Neopteryx frosti", "Haplonycteris fischeri", 
                          "Aproteles bulmerae", "Myonycteris brachycephala", "Myonycteris torquata", 
                          "Myonycteris relicta", "Balionycteris maculata", "Rousettus amplexicaudatus", 
                          "Rousettus spinalatus", "Rousettus madagascariensis", "Rousettus celebensis", 
                          "Rousettus aegyptiacus", "Rousettus obliviosus", "Hypsignathus monstrosus", 
                          "Pteralopex atrata", "Pteralopex pulchra", "Pteralopex anceps", 
                          "Eonycteris major", "Eonycteris spelaea", "Alionycteris paucidentata", 
                          "Latidens salimalii", "Aethalops alecto", "Paranyctimene raptor", 
                          "Syconycteris hobbit", "Syconycteris australis", "Syconycteris carolinae", 
                          "Notopteris macdonaldii", "Myzopoda aurita", "Eumops dabbenei", 
                          "Eumops auripendulus", "Eumops glaucinus", "Eumops maurus", "Eumops perotis", 
                          "Eumops underwoodi", "Eumops hansae", "Eumops bonariensis", "Molossops temminckii", 
                          "Molossops neglectus", "Tadarida teniotis", "Tadarida brasiliensis", 
                          "Tadarida lobata", "Tadarida ventralis", "Tadarida fulminans", 
                          "Tadarida aegyptiaca", "Otomops secundus", "Otomops papuensis", 
                          "Otomops formosus", "Otomops wroughtoni", "Otomops martiensseni", 
                          "Promops nasutus", "Promops centralis", "Cheiromeles torquatus", 
                          "Mormopterus phrudus", "Mormopterus minutus", "Mormopterus doriae", 
                          "Mormopterus acetabulosus", "Mormopterus kalinowskii", "Mormopterus jugularis", 
                          "Nyctinomops aurispinosus", "Nyctinomops macrotis", "Nyctinomops laticaudatus", 
                          "Nyctinomops femorosaccus", "Mops congicus", "Mops niangarae", 
                          "Mops sarasinorum", "Mops trevori", "Mops brachypterus", "Mops demonstrator", 
                          "Mops mops", "Mops niveiventer", "Mops spurrelli", "Mops condylurus", 
                          "Mops midas", "Mops nanulus", "Mops petersoni", "Mops thersites", 
                          "Saccolaimus mixtus", "Saccolaimus flaviventris", "Saccolaimus saccolaimus", 
                          "Saccolaimus peli", "Coleura seychellensis", "Coleura afra", 
                          "Diclidurus ingens", "Diclidurus scutatus", "Diclidurus albus", 
                          "Diclidurus isabella", "Rhynchonycteris naso", "Cormura brevirostris", 
                          "Emballonura dianae", "Emballonura alecto", "Emballonura beccarii", 
                          "Emballonura raffrayana", "Emballonura furax", "Emballonura semicaudata", 
                          "Emballonura monticola", "Balantiopteryx plicata", "Balantiopteryx io", 
                          "Balantiopteryx infusca", "Centronycteris maximiliani", "Cyttarops alecto", 
                          "Peropteryx macrotis", "Peropteryx leucoptera", "Peropteryx kappleri", 
                          "Centurio senex", "Erophylla sezekorni", "Erophylla bombifrons", 
                          "Scleronycteris ega", "Uroderma magnirostrum", "Uroderma bilobatum", 
                          "Choeroniscus minor", "Choeroniscus periosus", "Choeroniscus godmani", 
                          "Chiroderma trinitatum", "Chiroderma improvisum", "Chiroderma villosum", 
                          "Chiroderma doriae", "Chiroderma salvini", "Phylloderma stenops", 
                          "Diphylla ecaudata", "Carollia subrufa", "Carollia perspicillata", 
                          "Carollia brevicaudum", "Carollia castanea", "Vampyressa pusilla", 
                          "Vampyressa melissa", "Glossophaga longirostris", "Glossophaga commissarisi", 
                          "Glossophaga soricina", "Glossophaga leachii", "Glossophaga morenoi", 
                          "Tonatia bidens", "Choeronycteris mexicana", "Lonchorhina fernandezi", 
                          "Lonchorhina orinocensis", "Lonchorhina aurita", "Lonchorhina marinkellei", 
                          "Vampyrodes caraccioli", "Hylonycteris underwoodi", "Ectophylla alba", 
                          "Lonchophylla robusta", "Lonchophylla handleyi", "Lonchophylla bokermanni", 
                          "Lonchophylla mordax", "Lonchophylla hesperia", "Lonchophylla dekeyseri", 
                          "Ametrida centurio", "Lionycteris spurrelli", "Monophyllus plethodon", 
                          "Monophyllus redmani", "Lichonycteris obscura", "Pygoderma bilabiatum", 
                          "Platalina genovensium", "Artibeus obscurus", "Artibeus toltecus", 
                          "Artibeus aztecus", "Artibeus glaucus", "Artibeus hirsutus", 
                          "Artibeus phaeotis", "Artibeus amplus", "Artibeus cinereus", 
                          "Artibeus fimbriatus", "Artibeus inopinatus", "Artibeus lituratus", 
                          "Artibeus planirostris", "Artibeus jamaicensis", "Artibeus anderseni", 
                          "Artibeus concolor", "Artibeus fraterculus", "Ardops nichollsi", 
                          "Phyllostomus hastatus", "Phyllostomus discolor", "Phyllostomus elongatus", 
                          "Phyllostomus latifolius", "Micronycteris schmidtorum", "Micronycteris minuta", 
                          "Micronycteris hirsuta", "Micronycteris megalotis", "Macrotus waterhousii", 
                          "Macrotus californicus", "Desmodus rotundus", "Trachops cirrhosus", 
                          "Sphaeronycteris toxophyllum", "Phyllonycteris poeyi", "Phyllonycteris aphylla", 
                          "Ariteus flavescens", "Mimon bennettii", "Leptonycteris yerbabuenae", 
                          "Leptonycteris curasoae", "Leptonycteris nivalis", "Musonycteris harrisoni", 
                          "Sturnira bidens", "Sturnira erythromos", "Sturnira luisi", "Sturnira nana", 
                          "Sturnira lilium", "Sturnira magna", "Sturnira aratathomasi", 
                          "Sturnira bogotensis", "Sturnira ludovici", "Sturnira mordax", 
                          "Sturnira tildae", "Vampyrum spectrum", "Noctilio leporinus", 
                          "Noctilio albiventris", "Mystacina tuberculata", "Mystacina robusta", 
                          "Megaderma spasma", "Lavia frons", "Cardioderma cor", "Craseonycteris thonglongyai", 
                          "Thyroptera lavali", "Emballonura serii", "Centronycteris centralis", 
                          "Mimon cozumelae", "Artibeus gnomus", "Artibeus watsoni", "Enchisthenes hartii", 
                          "Trinycteris nicefori", "Vampyressa thyone", "Glyphonycteris behnii", 
                          "Glyphonycteris sylvestris", "Glyphonycteris daviesi", "Lonchorhina inusitata", 
                          "Sturnira mistratensis", "Sturnira oporaphilum", "Carollia sowelli", 
                          "Neonycteris pusilla", "Lampronycteris brachyotis", "Phyllonycteris major", 
                          "Micronycteris matses", "Micronycteris brosseti", "Micronycteris sanborni", 
                          "Mormoops magna", "Mormoops blainvillei", "Nyctiellus lepidus", 
                          "Natalus jamaicensis", "Natalus major", "Natalus primus", "Chilonatalus tumidifrons", 
                          "Dyacopterus brooksi", "Eonycteris robusta", "Notopteris neocaledonicus", 
                          "Aethalops aequalis", "Cynopterus luzoniensis", "Cynopterus minutus", 
                          "Plerotes anchietae", "Nanonycteris veldkampii", "Epomophorus crypturus", 
                          "Epomophorus minor", "Dobsonia anderseni", "Dobsonia crenulata", 
                          "Paranyctimene tenax", "Pteralopex taki", "Rousettus linduensis", 
                          "Bauerus dubiaquercus", "Kerivoula lenis", "Neoromicia zuluensis", 
                          "Arielulus circumdatus", "Arielulus societatis", "Arielulus cuprosus", 
                          "Histiotus laephotis", "Histiotus magellanicus", "Histiotus humboldti", 
                          "Eptesicus japonensis", "Eptesicus chiriquinus", "Eptesicus andinus", 
                          "Murina hilgendorfi", "Murina ryukyuana", "Scoteanax rueppellii", 
                          "Chalinolobus neocaledonicus", "Scotoecus albigula", "Falsistrellus tasmaniensis", 
                          "Falsistrellus mackenziei", "Cistugo lesueuri", "Cistugo seabrae", 
                          "Glauconycteris beatrix", "Glauconycteris gleni", "Glauconycteris machadoi", 
                          "Glauconycteris variegata", "Glauconycteris alboguttata", "Glauconycteris curryae", 
                          "Glauconycteris humeralis", "Glauconycteris poensis", "Glauconycteris argentata", 
                          "Glauconycteris egeria", "Glauconycteris kenyacola", "Glauconycteris superba", 
                          "Nyctophilus howensis", "Nyctophilus nebulosus", "Miniopterus manavi", 
                          "Miniopterus majori", "Miniopterus gleni", "Miniopterus africanus", 
                          "Miniopterus medius", "Miniopterus shortridgei", "Miniopterus macrocneme", 
                          "Vespadelus vulturnus", "Vespadelus pumilus", "Vespadelus darlingtoni", 
                          "Vespadelus troughtoni", "Vespadelus finlaysoni", "Vespadelus caurinus", 
                          "Vespadelus regulus", "Vespadelus douglasorum", "Vespadelus baverstocki", 
                          "Phoniscus papuensis", "Phoniscus aerosus", "Phoniscus jagorii", 
                          "Phoniscus atrox", "Hypsugo musciculus", "Hypsugo alaschanicus", 
                          "Hypsugo arabicus", "Hypsugo cadornae", "Hypsugo imbricatus", 
                          "Hypsugo lophurus", "Hypsugo pulveratus", "Hypsugo vordermanni", 
                          "Hypsugo ariel", "Hypsugo macrotis", "Hypsugo kitcheneri", "Myotis gomantongensis", 
                          "Myotis bucharensis", "Myotis laniger", "Myotis annamiticus", 
                          "Myotis punicus", "Myotis anjouanensis", "Myotis alcathoe", "Myotis davidii", 
                          "Myotis macropus", "Myotis occultus", "Myotis yanbarensis", "Myotis csorbai", 
                          "Myotis hermani", "Myotis fimbriatus", "Rhogeessa hussoni", "Rhogeessa aenea", 
                          "Rhogeessa io", "Scotorepens greyii", "Scotorepens balstoni", 
                          "Scotorepens sanborni", "Scotorepens orion", "Nycticeius cubanus", 
                          "Nycticeius aenobarbus", "Scotozous dormeri", "Mops leucostigma", 
                          "Otomops johnstonei", "Otomops madagascariensis", "Cheiromeles parvidens", 
                          "Cynomops mexicanus", "Cynomops planirostris", "Cynomops greenhalli", 
                          "Eumops trumbulli", "Tadarida insignis", "Tadarida latouchei", 
                          "Rhinolophus convexus", "Rhinolophus hillorum", "Rhinolophus hilli", 
                          "Rhinolophus hildebrandtii", "Rhinolophus ziama", "Rhinolophus siamensis", 
                          "Rhinolophus maendeleo", "Rhinolophus shortridgei", "Rhinolophus formosae", 
                          "Rhinolophus madurensis", "Rhinolophus sakejiensis", "Rhinolophus ruwenzorii", 
                          "Rhinolophus montanus", "Rhinolophus bocharicus", "Nyctophilus daedalus", 
                          "Cabreramops aequatorianus", "Lonchophylla concava", "Mormopterus stehlini", 
                          "Mormopterus helveticus", "Tadarida rusingae", "Tadarida constantinei", 
                          "Tadarida leptognatha", "Tadarida engesseri", "Saharaderma pseudovampyrus", 
                          "Megaderma vireti", "Megaderma brailloni", "Megaderma franconica", 
                          "Qarunycteris moerisae", "Rhinolophus pumilio", "Rhinolophus hanaki", 
                          "Rhinolophus dehmi", "Rhinolophus priscus", "Rhinolophus csakvarensis", 
                          "Rhinolophus wenzensis", "Rhinolophus lemanensis", "Rhinolophus grivensis", 
                          "Rhinolophus delphinensis", "Cubanycteris silvai", "Paleptesicus priscus", 
                          "Stehlinia gracilis", "Chadronycteris rabenae", "Shanwangia unexpectata", 
                          "Myotis boyeri", "Myotis helleri", "Myotis sanctialbani", "Myotis grisecens", 
                          "Myotis mangamolaris", "Myotis rectidens", "Myotis salodorensis", 
                          "Karstala silva", "Miostrellus risgoviensis", "Miomyotis floridanus", 
                          "Miniopterus tao", "Miniopterus fossilis", "Miniopterus approximatus", 
                          "Suaptenos whitei", "Potamonycteris biperforatus", "Khonsunycteris aegypticus", 
                          "Eptesicus praeglacialis", "Eptesicus kowalskii", "Eptesicus aurelianensis", 
                          "Eptesicus noctuloides", "Eptesicus mossoczyi", "Eptesicus campanensis", 
                          "Anzanycteris anzensis", "Archerops annectens", "Brevipalatus mcculloughi", 
                          "Asellia mariaetheresae", "Paraphyllophora robusta", "Xenorhinos halli", 
                          "Icaronycteris menui", "Icaronycteris index", "Tanzanycteris mannardi", 
                          "Archaeonycteris brailloni", "Cecilionycteris prisca", "Philisis sphingis", 
                          "Vampyravus orientalis", "Witwatia schlosseri", "Witwatia eremicus", 
                          "Desmodus stocki", "Onychonycteris finneyi", "Ageina tobieni", 
                          "Primonatalus prattae", "Honrovits tsuwape", "Archaeopteropus transiens", 
                          "Tachypteron franzeni", "Dhofarella sigei", "Propotto leakeyi", 
                          "Cambaya complexus", "Samonycteris majori", "Tomopeas ravus", 
                          "Pipistrellus coromandra", "Pipistrellus minahassae", "Pipistrellus stenopterus", 
                          "Pipistrellus aero", "Pipistrellus endoi", "Pipistrellus kuhlii", 
                          "Pipistrellus pipistrellus", "Pipistrellus nathusii", "Pipistrellus ceylonicus", 
                          "Pipistrellus maderensis", "Pipistrellus permixtus", "Pipistrellus nanulus", 
                          "Pipistrellus tenuis", "Pipistrellus javanicus", "Pipistrellus rusticus", 
                          "Pipistrellus inexspectatus", "Pipistrellus sturdeei", "Pipistrellus paterculus", 
                          "Plecotus auritus", "Plecotus taivanus", "Plecotus teneriffae", 
                          "Nyctalus leisleri", "Nyctalus azoreum", "Nyctalus noctula", 
                          "Nyctalus lasiopterus", "Nyctalus aviator", "Nyctalus montanus", 
                          "Scotophilus kuhlii", "Scotophilus dinganii", "Scotophilus viridis", 
                          "Scotophilus nigrita", "Scotophilus celebensis", "Scotophilus robustus", 
                          "Scotophilus leucogaster", "Scotophilus nux", "Lasiurus castaneus", 
                          "Lasiurus seminolus", "Lasiurus minor", "Lasiurus borealis", 
                          "Lasiurus blossevillii", "Coelops robinsoni", "Hipposideros lankadiva", 
                          "Hipposideros ruber", "Hipposideros dinops", "Hipposideros maggietaylorae", 
                          "Hipposideros speoris", "Hipposideros fulvus", "Hipposideros obscurus", 
                          "Hipposideros coronatus", "Hipposideros ridleyi", "Hipposideros ater", 
                          "Hipposideros diadema", "Hipposideros macrobullatus", "Hipposideros calcaratus", 
                          "Hipposideros fuliginosus", "Hipposideros lamottei", "Hipposideros pygmaeus", 
                          "Hipposideros armiger", "Hipposideros lylei", "Hipposideros caffer", 
                          "Hipposideros nequam", "Hipposideros jonesi", "Hipposideros pratti", 
                          "Hipposideros abae", "Hipposideros curtus", "Hipposideros lekaguli", 
                          "Hipposideros breviceps", "Hipposideros cineraceus", "Hipposideros inexpectatus", 
                          "Hipposideros pomona", "Hipposideros crumeniferus", "Hipposideros bicolor", 
                          "Hipposideros dyacorum", "Hipposideros megalotis", "Hipposideros turpis", 
                          "Hipposideros cervinus", "Hipposideros halophyllus", "Hipposideros papua", 
                          "Hipposideros coxi", "Hipposideros larvatus", "Hipposideros beatus", 
                          "Hipposideros doriae", "Hipposideros marisae", "Hipposideros galeritus", 
                          "Nycteris arge", "Nycteris hispida", "Nycteris macrotis", "Nycteris tragata", 
                          "Nycteris gambiensis", "Nycteris intermedia", "Nycteris major", 
                          "Nycteris thebaica", "Nycteris woodi", "Nycteris grandis", "Nycteris javanica", 
                          "Nycteris nana", "Pteronotus personatus", "Pteronotus parnellii", 
                          "Pteronotus macleayii", "Pteronotus davyi", "Pteronotus quadridens", 
                          "Pteronotus gymnonotus", "Macroglossus minimus", "Macroglossus sobrinus", 
                          "Nyctimene masalai", "Nyctimene rabori", "Nyctimene vizcaccia", 
                          "Nyctimene aello", "Nyctimene albiventer", "Nyctimene certans", 
                          "Nyctimene major", "Nyctimene robinsoni", "Nyctimene cyclotis", 
                          "Nyctimene malaitensis", "Nyctimene cephalotes", "Nyctimene draconilla", 
                          "Pteropus nitendiensis", "Pteropus vampyrus", "Pteropus rodricensis", 
                          "Pteropus pselaphon", "Pteropus aldabrensis", "Pteropus caniceps", 
                          "Pteropus scapulatus", "Pteropus tokudae", "Pteropus fundatus", 
                          "Pteropus niger", "Pteropus tuberculatus", "Pteropus poliocephalus", 
                          "Pteropus brunneus", "Pteropus mahaganus", "Pteropus samoensis", 
                          "Pteropus faunulus", "Pteropus hypomelanus", "Pteropus pohlei", 
                          "Pteropus woodfordi", "Pteropus macrotis", "Pteropus pilosus", 
                          "Pteropus dasymallus", "Pteropus neohibernicus", "Pteropus howensis", 
                          "Pteropus tonganus", "Pteropus personatus", "Pteropus voeltzkowi", 
                          "Pteropus admiralitatum", "Pteropus anetianus", "Pteropus lylei", 
                          "Pteropus conspicillatus", "Pteropus melanotus", "Pteropus subniger", 
                          "Pteropus griseus", "Pteropus ornatus", "Pteropus vetula", "Pteropus alecto", 
                          "Pteropus lombocensis", "Pteropus rayneri", "Pteropus molossinus", 
                          "Pteropus melanopogon", "Pteropus speciosus", "Pteropus ocularis", 
                          "Pteropus livingstonii", "Pteropus pumilus", "Pteropus mariannus", 
                          "Pteropus chrysoproctus", "Pteropus seychellensis", "Acerodon macklotii", 
                          "Acerodon jubatus", "Acerodon celebensis", "Acerodon humilis", 
                          "Acerodon leucotis", "Myopterus whitleyi", "Myopterus daubentonii", 
                          "Chaerephon nigeriae", "Chaerephon bemmeleni", "Chaerephon gallagheri", 
                          "Chaerephon johorensis", "Chaerephon aloysiisabaudiae", "Chaerephon jobensis", 
                          "Chaerephon major", "Chaerephon ansorgei", "Chaerephon chapini", 
                          "Molossus pretiosus", "Molossus molossus", "Molossus bondae", 
                          "Molossus sinaloae", "Saccopteryx canescens", "Saccopteryx leptura", 
                          "Saccopteryx bilineata", "Saccopteryx gymnura", "Mosia nigrescens", 
                          "Taphozous hamiltoni", "Taphozous hildegardeae", "Taphozous longimanus", 
                          "Taphozous nudiventris", "Taphozous theobaldi", "Taphozous australis", 
                          "Taphozous hilli", "Taphozous mauritianus", "Taphozous perforatus", 
                          "Taphozous georgianus", "Taphozous kapalgensis", "Taphozous melanopogon", 
                          "Rhinopoma muscatellum", "Rhinopoma microphyllum", "Phyllops falcatus", 
                          "Macrophyllum macrophyllum", "Chrotopterus auritus", "Stenoderma rufum", 
                          "Mesophylla macconnelli", "Rhinophylla fischerae", "Rhinophylla alethina", 
                          "Rhinophylla pumilio", "Brachyphylla cavernarum", "Brachyphylla nana", 
                          "Platyrrhinus helleri", "Platyrrhinus vittatus", "Platyrrhinus lineatus", 
                          "Platyrrhinus brachycephalus", "Platyrrhinus aurarius", "Platyrrhinus umbratus", 
                          "Platyrrhinus infuscus", "Platyrrhinus dorsalis", "Platyrrhinus recifinus", 
                          "Macroderma gigas", "Taphozous troughtoni", "Saccopteryx antioquensis", 
                          "Lophostoma silvicola", "Lophostoma carrikeri", "Lophostoma schulzi", 
                          "Lophostoma brasiliense", "Lophostoma evotis", "Pteronotus pristinus", 
                          "Hipposideros demissus", "Hipposideros sorenseni", "Hipposideros pelingensis", 
                          "Hipposideros inornatus", "Hipposideros scutinares", "Hipposideros orbiculus", 
                          "Hipposideros hypophyllus", "Hipposideros grandis", "Hipposideros durgadasi", 
                          "Hipposideros rotalis", "Pteropus pelewensis", "Pteropus temminckii", 
                          "Pteropus cognatus", "Pteropus ualanus", "Pteropus keyensis", 
                          "Pteropus gilliardorum", "Pteropus aruensis", "Pteropus rennelli", 
                          "Scotophilus collinus", "Scotophilus heathii", "Scotophilus nucella", 
                          "Nyctalus furvus", "Pipistrellus abramus", "Pipistrellus westralis", 
                          "Pipistrellus wattsi", "Pipistrellus pygmaeus", "Pipistrellus papuanus", 
                          "Pipistrellus collinus", "Pipistrellus adamsi", "Plecotus balensis", 
                          "Lasiurus ebenus", "Lasiurus pfeifferi", "Lasiurus varius", "Lasiurus atratus", 
                          "Lasiurus degelidus", "Chaerephon plicatus", "Chaerephon pumilus", 
                          "Chaerephon solomonis", "Chaerephon bregullae", "Chaerephon leucogaster", 
                          "Chaerephon russatus", "Chaerephon bivittatus", "Chaerephon tomensis", 
                          "Molossus aztecus", "Molossus currentium", "Molossus rufus", 
                          "Molossus coibensis", "Nycteris madagascariensis", "Nycteris aurita", 
                          "Rhinopoma hardwickii", "Rhinopoma macinnesi", "Murina gracilis", 
                          "Murina recondita", "Murina bicolor", "Harpiola isodon", "Plecotus sardus", 
                          "Plecotus austriacus", "Plecotus kolombatovici", "Myzopoda schliemanni", 
                          "Hipposideros khaokhouayensis", "Hipposideros boeadii", "Hipposideros nicobarulae", 
                          "Thyroptera devivoi", "Eumops floridanus", "Chaerephon pusillus", 
                          "Pteronotus paraguanensis", "Xeronycteris vieirai", "Artibeus rosenbergi", 
                          "Platyrrhinus ismaeli", "Platyrrhinus matapalensis", "Platyrrhinus masu", 
                          "Platyrrhinus albericoi", "Sturnira sorianoi", "Carollia manu", 
                          "Lonchophylla orcesi", "Lonchophylla chocoana", "Desmodus draculae", 
                          "Natalus lanatus", "Natalus mexicanus", "Rhinolophus andamanensis", 
                          "Rhinolophus petersii", "Rhinolophus perniger", "Rhinolophus perditus", 
                          "Rhinolophus pumilus", "Rhinolophus minor", "Pteralopex flanneryi", 
                          "Epomophorus anselli", "Styloctenium mindorensis", "Mirimiri acrodonta", 
                          "Pteropus medius", "Myotis pilosus", "Myotis dieteri", "Myotis peytoni", 
                          "Myotis longicaudatus", "Myotis rufopictus", "Eptesicus isabellinus", 
                          "Eptesicus anatolicus", "Pipistrellus murrayi", "Pipistrellus raceyi", 
                          "Pipistrellus hanaki", "Scotophilus tandrefana", "Scotophilus marovaza", 
                          "Kerivoula malpasi", "Kerivoula crypta", "Kerivoula depressa", 
                          "Kerivoula titania", "Kerivoula kachinensis", "Kerivoula krauensis", 
                          "Murina harrisoni", "Miniopterus fuliginosus", "Miniopterus griveaudi", 
                          "Miniopterus sororculus", "Miniopterus petersoni", "Miniopterus newtoni", 
                          "Barbastella caspica", "Nyctophilus sherrini", "Plecotus ognevi", 
                          "Plecotus macrobullaris", "Plecotus sacrimontis", "Plecotus christii", 
                          "Harpiola grisea", "Lasiurus fossilis", "Plecotus atavus", "Plecotus crassidens", 
                          "Plecotus rabederi", "Hipposideros aguilari", "Hipposideros dechaseauxi", 
                          "Hipposideros collongensis", "Hipposideros bouziguensis", "Anoura latidens", 
                          "Anoura caudifer", "Anoura geoffroyi", "Anoura cultrata", "Anoura luismanueli", 
                          "Anoura fistulata", "Taphozous achates", "Peropteryx trinitatis", 
                          "Tonatia saurophila", "Micronycteris microtis", "Coelops frithii", 
                          "Hipposideros madurae", "Hipposideros sumbae", "Chilonatalus micropus", 
                          "Lissonycteris angolensis", "Nyctimene keasti", "Cynopterus horsfieldii", 
                          "Dobsonia peronii", "Rousettus leschenaultii", "Pteropus capistratus", 
                          "Neoromicia guineensis", "Vespertilio sinensis", "Nyctalus plancyi", 
                          "Eptesicus gobiensis", "Eptesicus nilssonii", "Scotoecus hindei", 
                          "Pipistrellus hesperidus", "Pipistrellus angulatus", "Nyctophilus bifax", 
                          "Miniopterus paululus", "Miniopterus natalensis", "Hypsugo savii", 
                          "Myotis ater", "Myotis moluccarum", "Myotis brandtii", "Myotis bocagii", 
                          "Myotis nipalensis", "Cynomops abrasus", "Platymops setiger", 
                          "Sauromys petrophilus", "Eumops patagonicus", "Nycteris parisii", 
                          "Rhinolophus sinicus", "Rhinolophus beddomei", "Myotis rufoniger", 
                          "Platyrrhinus incarum", "Murina walstoni", "Hipposideros einnaythu", 
                          "Asellia arabica", "Diaemus youngii", "Hsunycteris thomasi", 
                          "Uroderma convexum", "Rhinolophus proconsulis", "Lonchophylla orienticollina", 
                          "Rhinolophus chiewkweeae", "Murina guilleni", "Micronycteris giovanniae", 
                          "Sturnira perla", "Platyrrhinus guianensis", "Myotis handleyi", 
                          "Mormopterus francoismoutoui", "Epomophorus pusillus", "Neoplatymops mattogrossensis", 
                          "Paremballonura atrata", "Tylonycteris pygmaea", "Dryadonycteris capixaba", 
                          "Lonchophylla fornicata", "Rhinolophus willardi", "Rhinolophus cohenae", 
                          "Miniopterus egeri", "Miniopterus pallidus", "Myotis sibiricus", 
                          "Hipposideros pendleburyi", "Rhinopoma hadramauticum", "Scotophilus livingstonii", 
                          "Triaenops menamena", "Desmalopex microleucopterus", "Murina chrysochaetes", 
                          "Paratriaenops auritus", "Myotis izecksohni", "Otonycteris leucophaea", 
                          "Eumops wilsoni", "Myotis lavali", "Carollia monohernandezi", 
                          "Lophostoma kalkoae", "Hipposideros alongensis", "Casinycteris ophiodon", 
                          "Miniopterus mahafaliensis", "Scotophilus trujilloi", "Sturnira paulsoni", 
                          "Perimyotis subflavus", "Thyroptera wynneae", "Murina shuipuensis", 
                          "Anoura aequatoris", "Scotophilus ejetai", "Pteropus rufus", 
                          "Uroderma bakeri", "Mops bakarii", "Rhinolophus microglobosus", 
                          "Murina lorelieae", "Nyctophilus shirleyae", "Thoopterus suhaniahae", 
                          "Glischropus aquilus", "Rhinolophus smithersi", "Barbastella beijingensis", 
                          "Glischropus bucephalus", "Paratriaenops pauliani", "Nycticeinops schlieffenii", 
                          "Sturnira parvidens", "Rhinolophus horaceki", "Mystacina velutina", 
                          "Lonchophylla peracchii", "Coleura kibomalandy", "Hsunycteris pattoni", 
                          "Molossus alvarezi", "Rhinolophus mabuensis", "Natalus macrourus", 
                          "Murina eleryi", "Plecotus turkmenicus", "Platyrrhinus fusciventris", 
                          "Sturnira angeli", "Murina annamitica", "Plecotus homochrous", 
                          "Murina fionae", "Myotis midastactus", "Hsunycteris cadenai", 
                          "Vampyriscus nymphaea", "Rhinolophus schnitzleri", "Miniopterus mossambicus", 
                          "Plecotus kozlovi", "Triaenops parvus", "Sturnira hondurensis", 
                          "Paremballonura tiavato", "Chilonatalus macer", "Rhinolophus xinanzhongguoensis", 
                          "Plecotus strelkovi", "Murina feae", "Rhinolophus kahuzi", "Neoromicia somalica", 
                          "Dyacopterus rickarti", "Myotis diminutus", "Eptesicus taddeii", 
                          "Chaerephon jobimena", "Myotis indochinensis", "Anoura cadenai", 
                          "Artibeus aequatorialis", "Plecotus wardi", "Rhinolophus mossambicus", 
                          "Eumops nanus", "Artibeus schwartzi", "Sturnira bakeri", "Carollia benkeithi", 
                          "Myotis badius", "Paratriaenops furcula", "Epomophorus dobsonii", 
                          "Miniopterus brachytragos", "Miniopterus griffithsi", "Rhinolophus tatar", 
                          "Sturnira koopmanhilli", "Triaenops afer", "Rhinolophus belligerator", 
                          "Rhinolophus mcintyrei", "Pteronotus rubiginosus", "Asellia italosomalica", 
                          "Hypsugo lanzai", "Miniopterus maghrebensis", "Rhogeessa menchuae", 
                          "Anoura peruana", "Murina beelzebub", "Myotis petax", "Nyctophilus corbeni", 
                          "Myotis escalerai", "Rhogeessa bickhami", "Hipposideros griffini", 
                          "Artibeus bogotensis", "Rhinolophus damarensis", "Murina peninsularis", 
                          "Micronycteris yatesi", "Sturnira burtonlimi", "Pteropus coxi", 
                          "Myotis annatessae", "Megaloglossus azagnyi", "Myotis phanluongi", 
                          "Chaerephon atsinanana", "Pteropus allenorum", "Thainycteris aureocollaris", 
                          "Eumops delticus", "Murina balaensis", "Murina huttonii", "Rhinolophus thailandensis", 
                          "Uroderma davisi", "Miniopterus aelleni", "Scotophilus andrewreborii", 
                          "Wallia scalopidens", "Rhinopoma cystops", "Vampyriscus brocki", 
                          "Pteropus myoti", "Murina harpioloides", "Casinycteris campomaanensis", 
                          "Desmalopex leucopterus", "Parastrellus hesperus", "Vampyriscus bidens", 
                          "Nyctophilus major", "Dhofarella thaleri", "Vesperugo anemophilus", 
                          "Hypsugo dolichodon", "Eudiscoderma thongareeae", "Eumops chiribaya", 
                          "Chibanycteris herberti", "Tadarida laticaudata", "Glossophaga apolinari", 
                          "Microchiropteryx folieae", "Rhinolophus yongyuthi", "Notonycteris magdalenensis", 
                          "Mystacina miocenalis", "Archaeonycteris relicta", "Potamops mascahehenes", 
                          "Submyotodon latirostris", "Hipposideros omani", "Hipposideros felix", 
                          "Phyllops silvai", "Ia lamna", "Otomops harrisoni", "Hipposideros khengakao", 
                          "Australonycteris clarkae", "Icaronycteris sigei", "Hassianycteris kumari", 
                          "Miniopterus ambohitrensis", "Archaeonycteris storchi", "Thyroptera robusta", 
                          "Protonycteris gunnelli", "Histiotus diaphanopterus", "Kiotomops lopezi", 
                          "Dizzya exsultans", "Palynephyllum antimaster", "Noctilio lacrimaelunaris", 
                          "Desmodus archaeodaptes", "Notonycteris sucharadeus", "Eumops ferox", 
                          "Vampyressa elisabethae", "Myotis larensis", "Platyrrhinus nitelinea", 
                          "Scotophilus nigritellus", "Rhinolophus episcopus", "Rhinolophus achilles", 
                          "Lonchophylla inexpectata", "Rhinolophus morio", "Vampyrodes major", 
                          "Speonycteris aurantiadens", "Murina kontumensis", "Myotis misonnei", 
                          "Rhinolophus nippon", "Diphylla centralis", "Cynomops milleri", 
                          "Kerivoula brasiliensis", "Glossophaga mutica", "Myotis dinellii", 
                          "Myotis browni", "Molossus milleri", "Rhinolophus francisi", 
                          "Nyctimene varius", "Rhinolophus refulgens", "Khoufechia gunnelli", 
                          "Platyrrhinus angustirostris", "Myotis sowerbyi", "Vespertiliavus kasserinensis", 
                          "Drakonycteris glibzegdouensis", "Rhinolophus truncatus", "Noctilio americanus", 
                          "Miniopterus horaceki", "Gardnerycteris crenulatum", "Kerivoula bicolor", 
                          "Myotis darelbeidensis", "Hipposideros gentilis", "Phasmatonycteris phiomensis", 
                          "Phasmatonycteris butleri", "Necromantis fragmentum", "Speonycteris naturalis", 
                          "Tylonycteris malayana", "Promops davisoni", "Nesonycteris woodfordi", 
                          "Pteronotus mesoamericanus", "Pseudovespertiliavus parva", "Rhinolophus chaseni", 
                          "Palaeophyllophora tunisiensis", "Scotonycteris bergmansi", "Eptesicus ognevi", 
                          "Trachops fuliginosus", "Peropteryx pallidoptera", "Molossus verrilli", 
                          "Vampyressa sinchi", "Otonycteris rummeli", "Corynorhinus alleganiensis", 
                          "Rhinolophus maghrebensis", "Vespertiliavus aenigma", "Pteropus pelagicus", 
                          "Madataeus lewisii", "Hipposideros tephrus", "Simonycteris stocki", 
                          "Chambinycteris pusilli", "Rhinolophus lobatus", "Kerivoula pusilla", 
                          "Stehlinia bonisi", "Myotis secundus", "Vaylatsia prisca", "Murina hkakaboraziensis", 
                          "Vespertiliavus gracilis", "Myotis attenboroughi", "Tylonycteris tonkinensis", 
                          "Rhinolophus lugdunensis", "Rhinolophus lakkhanae", "Mixopteryx weithoferi", 
                          "Dasypterus golliheri", "Pipistrellus taiwanensis", "Adapisorex anglicus", 
                          "Lapichiropteryx xiei", "Hipposideros bernardsigei", "Vespertilio murinoides", 
                          "Sturnira adrianae", "Palaeophyllophora oltina", "Hsunycteris dashe", 
                          "Mixopteryx dubia", "Miophyllorhina riversleighensis", "Rhinolophus collongensis", 
                          "Nyctimene celoeno", "Xeronycteris vierai", "Artibeus ravus", 
                          "Corynorhinus tetralophodon", "Hipposideros africanum", "Vespertiliavus lapradei", 
                          "Macroderma koppa", "Eumops chimaera", "Cassistrellus yokdonensis", 
                          "Riversleigha williamsi", "Myotis soror", "Aegyptonycteris knightae", 
                          "Palaeophyllophora quercyi", "Lonchorhina mankomara", "Vespertilio antiquus", 
                          "Hipposideros morloti", "Myotis belgicus", "Archaeonycteris praecursor", 
                          "Pseudorhinolophus schlosseri", "Tylonycteris eremtaga", "Pipistrellus montanus", 
                          "Gardnerycteris koepckeae", "Vespertilio spec", "Necromantis adichaster", 
                          "Vespertilio oedilis", "Myotis mystacinus", "Miniopterus schreibersii", 
                          "Pteronotus alitonus", "Eptesicus chapmani", "Myotis crypticus", 
                          "Myotis zenatius", "Koopmanycteris palaeomormoops", "Barbastella darjelingensis", 
                          "Myotis ancricola", "Myonycteris leptodon", "Eptesicus ulapesensis", 
                          "Anatolianycteris insularis", "Phoniscus rapax", "Barbastella pacifica", 
                          "Stenonycteris lanosus", "Hypsugo petersi", "Doryrhina edwardshilli", 
                          "Doryrhina stenotis", "Rhinolophus rhodesiae", "Laephotis kirinyaga", 
                          "Murina jaintiana", "Dasypterus ega", "Aselliscus dongbacanus", 
                          "Emballonura seni", "Eptesicus pachyomus", "Rhinolophus cognotus", 
                          "Lichonycteris degener", "Nanonycteris macrotis", "Miniopterus nimbae", 
                          "Hipposideros khasiana", "Chiroderma scopaeum", "Micronycteris buriri", 
                          "Hipposideros arpiocephalus", "Hipposideros macrobullotus", "Rhinolophus hipposiderus", 
                          "Scotophilus altilis", "Rhogeessa velilla", "Lasiurus blossebillii", 
                          "Myotis borneoensis", "Lyroderma lyra", "Rhinolophus gorongosae", 
                          "Doryrhina cyclops", "Rhinolophus vulgaris", "Nanonycteris intermedia", 
                          "Rhinolophus deckend", "Hipposideros griffoni", "Micronycteris simmonsae", 
                          "Balantiopteryx infosca", "Rhinolophus geoffroyii", "Ozimops loriae", 
                          "Nanonycteris arge", "Dasypterus insularis", "Rhinolophus murinus", 
                          "Doryrhina wollastoni", "Macronycteris gigas", "Anoura javieri", 
                          "Rhinolophus indorouxii", "Rhinolophus spec", "Austronomus australis", 
                          "Rhinolophus dobsoni", "Rhinolophus luctoides", "Balionycteris seimundi", 
                          "Gardnerycteris keenani", "Doryrhina semoni", "Myotis federatus", 
                          "Sturnira giannae", "Pteropus pyrivorus", "Myotis nimbaensis", 
                          "Pseudoromicia nyanza", "Hipposideros kunzi", "Rhinolophus bembanicus", 
                          "Hipposideros ceruinus", "Hypsugo affinis", "Nanonycteris thebaica", 
                          "Chiroderma gorgasi", "Macronycteris commersonii", "Myotis nyctor", 
                          "Nycticeinops hispida", "Rhinolophus luetus", "Rhinolophus etjryale", 
                          "Rhinolophus comutus", "Emballonura beccarli", "Rhinolophus brockmani", 
                          "Doryrhina muscinus", "Murina pluvialis", "Rhinolophus diadema", 
                          "Rhinolophus monticolus", "Macronycteris vittatus", "Tonatia bakeri", 
                          "Rhinolophus nanus", "Harpyiocephalus esperoptenus", "Hipposideros ipposideros", 
                          "Tonatia maresi", "Rhinolophus alticolus", "Rhinolophus insignis", 
                          "Aselliscus major", "Ozimops petersi", "Doryrhina camerunensis", 
                          "Rhinolophus axillaris", "Micronycteris tresamici", "Anthops omatus", 
                          "Rhinolophus odami", "Rhinolophus ferrum-eqtjinum", "Micronomus norfolkensis", 
                          "Rhinolophus lanosus", "Macronycteris thomensis", "Kerivoula furva", 
                          "Macronycteris cryptovalorona", "Rhyneptesicus nasutus", "Glauconycteris atra", 
                          "Plecotus gaisleri", "Doryrhina corynophyllus", "Lasiurus arequipae", 
                          "Pseudoromicia kityoi", "Austronomus kuboriensis", "Cynomops mastivus", 
                          "Aeorestes villosissimus", "Platyrrhinus aquilus", "Coleura gallarum", 
                          "Palaeochiropteryx tupaiodon", "Nycticeinops grandidieri", "Dasypterus xanthinus", 
                          "Nesonycteris fardoulisi", "Murina jinchui", "Aeorestes egregius", 
                          "Pteropus ennisae", "Nyctimene wrightae", "Myotis pilosatibialis", 
                          "Vampyressa voragine", "Cardioderma leakeyi", "Mirostrellus joffrei", 
                          "Nycticeinops bellieri", "Scotophilisis libycus", "Ptenochirus wetmorei", 
                          "Myotis bartelsii", "Hipposideros conquensis", "Quinetia frigidaria", 
                          "Boneia menadensis", "Myotis weberi", "Hanakia agadjaniani", 
                          "Myotis clydejonesi", "Laephotis stanleyi", "Myotis tschuliensis", 
                          "Myotis bakeri", "Aeorestes cinereus", "Submyotodon moupinensis", 
                          "Mops turkwellensis", "Dasypterus intermedius", "Pteronotus pusillus", 
                          "Thainycteris torquatus", "Megaerops albicollis", "Myotis alticraniatus", 
                          "Pseudoromicia roseveari", "Pteronotus mexicanus", "Vespertilio praeglacialis", 
                          "Pipistrellus simandouensis", "Pteronotus fulvus", "Laephotis matroka", 
                          "Pipistrellus dhofarensis", "Tylonycteris fulvida", "Witwatia sigei", 
                          "Scotophilus colias", "Laephotis malagasyensis", "Nycticeinops happoldorum", 
                          "Myotis caucensis", "Chironax tumulus", "Nycticeinops macrocephalus", 
                          "Myotis baranensis", "Myotis hyrcanicus", "Mops kerio", "Afronycteris helios", 
                          "Pseudoromicia tenuipinnis", "Turkanycteris harrisi", "Nycticeinops crassulus", 
                          "Nycticeinops serengetiensis", "Pteronotus psilotis", "Murina fanjingshanensis", 
                          "Rhogeessa permutandis", "Nycticeinops eisentrauti", "Laephotis capensis", 
                          "Lasiurius ega", "Taphozous incognita", "Murina liboensis", "Pteronotus fuscus", 
                          "Neoromicia anchietae", "Laephotis robertsi", "Epomophorus intermedius", 
                          "Scotoecus olduvensis", "Rousettus pattersoni", "Murina rongjiangensis", 
                          "Lophostoma occidentale", "Saccolaimus kenyensis", "Pseudoromicia isabella", 
                          "Glossophaga valens", "Rhinolophus contrarius", "Palaeochiropteryx spiegeli", 
                          "Pseudoromicia rendalli", "Vespertilio sylvicola", "Nyctophilus holtorum", 
                          "Pseudoromicia brunnea", "Macroderma handae", "Afronycteris nanus", 
                          "Lasiurus frantzii", "Submyotodon caliginosus", "Scotonycteris occidentalis", 
                          "Hypsugo mordax", "Myzopoda africana", "Pipistrellus creticus", 
                          "Vespertilio majori", "Aeorestes semotus", "Philisis sevketi", 
                          "Hipposideros minor", "Megaderma lopezae", "Pteronotus portoricensis", 
                          "Myotis hoveli", "Neoromicia bemainty", "Vansonia rueppellii", 
                          "Glossophaga antillarum", "Kerivoula dongduongana", "Myotis armiensis", 
                          "Chamtwaria pickfordi", "Cassistrellus dimissus", "Ozimops ridei", 
                          "Stehlinia quercyi", "Molossus fentoni", "Ozimops planiceps", 
                          "Miniopterus orianae", "Ozimops beccarii", "Miniopterus arenarius", 
                          "Miniopterus wilsoni", "Cynomops freemani", "Molossus fluminensis", 
                          "Cynomops kuizha", "Ozimops kitcheneri", "Ozimops lumsdenae", 
                          "Mops leucogaster", "Miniopterus blepotis", "Molossus nigricans", 
                          "Molossus melini", "Ozimops cobourgianus", "Miniopterus villiersi", 
                          "Cynomops tonkigui", "Ozimops halli", "Setirostris eleryi", "Miniopterus eschscholtzii"
  ), abb = c("RHOTUM", "RHOMIN", "RHOGEN", "RHOPAR", "RHOALL", 
             "RHOMIR", "RHOGRA", "SCOORN", "PHIBRA", "CHADWY", "CHAGOU", "CHANIG", 
             "CHATUB", "CHAPIC", "CHAMOR", "HISMON", "HISMAC", "HISVEL", "HISALI", 
             "LAENAM", "LAEWIN", "LAEBOT", "LAEANG", "NYCHUM", "PHAIMO", "MURAEN", 
             "MURFLO", "MURPUT", "MURSUI", "MURUSS", "MURAUR", "MURFUS", "MURROZ", 
             "MURTEN", "MURCYC", "MURLEU", "MURTUB", "SCOPAL", "SCOHIR", "SCOALB", 
             "ANTPAL", "LASNOC", "TYLPAC", "TYLROB", "EPTBOT", "EPTGUA", "EPTFUS", 
             "EPTINN", "EPTSER", "EPTTAT", "EPTFUR", "EPTHOT", "EPTPLA", "EPTBRA", 
             "EPTDIM", "EPTFLO", "EPTPAC", "HARHAR", "OTOHEM", "MYORIP", "MYOVEL", 
             "MYOHOR", "MYONAT", "MYOLEV", "MYOVIV", "MYOANN", "MYOELE", "MYORID", 
             "MYOTHY", "MYOHAS", "MYOSCO", "MYOCHI", "MYOTRI", "MYOLUC", "MYOALT", 
             "MYODOM", "MYOMAR", "MYOVOL", "MYOEVO", "MYOBLY", "MYOGOU", "MYOMYO", 
             "MYOSCH", "MYOSOD", "MYOCHI", "MYOKEA", "MYOFOR", "MYOOXY", "MYOSTA", 
             "MYOALB", "MYOCAL", "MYOPRU", "MYOBEC", "MYOFRA", "MYOMUR", "MYOCAP", 
             "MYOIKO", "MYOGRI", "MYOORE", "MYOSIM", "MYOKEE", "MYOSEP", "MYOAUR", 
             "MYODAU", "MYOMAC", "MYOPLA", "MYOAUS", "MYOFOR", "MYOMOR", "MYORUB", 
             "MYOINS", "MYONIG", "MYOSIL", "MYOADV", "MYOAUS", "MYODAS", "MYOMAC", 
             "MYOPEQ", "MYOLEI", "MYOCIL", "MYOATA", "MYOFIN", "MYOMON", "MYOROS", 
             "MYOYUM", "MYOBOM", "MYONES", "MYOSIC", "MYOCOB", "MYOLON", "MYOPEN", 
             "MYOWEL", "MYOEMA", "CORTOW", "CORMEX", "CORRAF", "MINROB", "MINMAG", 
             "MINFRA", "MINTRI", "MINPUS", "MININF", "MINAUS", "MINMIN", "MINFUS", 
             "GLIJAV", "GLITYL", "NYCWAL", "NYCGOU", "NYCMIC", "NYCGEO", "NYCHER", 
             "NYCMIC", "NYCARN", "IDIPHY", "MIMMOL", "HESTOM", "HESGAS", "HESTIC", 
             "HESDOR", "HESBLA", "KERWHI", "KERAGN", "KERCUP", "KERFLO", "KERMIN", 
             "KERPAP", "KERPEL", "KERPIC", "KERARG", "KERERI", "KERHAR", "KERMUS", 
             "KERPHA", "KERSMI", "KERAFR", "KERINT", "KERLAN", "KERMYR", "EUDDEN", 
             "VESMUR", "IAIO", "EUDMAC", "BARLEU", "BARBAR", "ASESTO", "ASETRI", 
             "ASEPAT", "ASETRI", "ANTORN", "RHISIL", "RHICEL", "RHIHIP", "RHIOSG", 
             "RHISUB", "RHICRE", "RHILEP", "RHIREX", "RHIEUR", "RHIMEG", "RHISHA", 
             "RHISUB", "RHIACU", "RHICOR", "RHILAN", "RHIYUN", "RHIALC", "RHIELO", 
             "RHIMAR", "RHICAP", "RHIGUI", "RHINER", "RHISTH", "RHICOG", "RHIKEY", 
             "RHIPUS", "RHIVIR", "RHIAFF", "RHIMAL", "RHISED", "RHICAN", "RHIFUM", 
             "RHIMON", "RHICOE", "RHIINO", "RHIPHI", "RHITRI", "RHIDEN", "RHIMAC", 
             "RHIRUF", "RHIBOR", "RHIFER", "RHIMIT", "RHISIM", "RHIPEA", "RHITHO", 
             "RHIADA", "RHIDEC", "RHIMAC", "RHIROU", "RHIBLA", "RHIMEH", "RHICLI", 
             "RHISWI", "RHIDAR", "RHILUC", "RHIROB", "RHIARC", "RHIEUR", "CLOPER", 
             "TRIPER", "RHIAUR", "NATTUM", "NATSTR", "MORMEG", "FURHOR", "AMOSCH", 
             "THYTRI", "THYDIS", "DYASPA", "SCOZEN", "THONIG", "EPOANG", "EPOWAH", 
             "EPOGRA", "EPOGAM", "EPOLAB", "MELMEL", "MEGWOE", "EPOFRA", "EPOBUE", 
             "DOBPRA", "DOBMOL", "DOBEXO", "DOBMIN", "DOBCHA", "DOBVIR", "DOBPAN", 
             "DOBINE", "DOBEME", "DOBBEA", "CYNTIT", "CYNSPH", "CYNBRA", "CYNNUS", 
             "HARWHI", "HARCEL", "BONBID", "CHIMEL", "PTEJAG", "PTEMIN", "EIDDUP", 
             "EIDHEL", "CASARG", "SPHBLA", "MEGKUS", "MEGNIP", "MEGECA", "OTOCAR", 
             "STYWAL", "PENLUC", "NEOFRO", "HAPFIS", "APRBUL", "MYOBRA", "MYOTOR", 
             "MYOREL", "BALMAC", "ROUAMP", "ROUSPI", "ROUMAD", "ROUCEL", "ROUAEG", 
             "ROUOBL", "HYPMON", "PTEATR", "PTEPUL", "PTEANC", "EONMAJ", "EONSPE", 
             "ALIPAU", "LATSAL", "AETALE", "PARRAP", "SYCHOB", "SYCAUS", "SYCCAR", 
             "NOTMAC", "MYZAUR", "EUMDAB", "EUMAUR", "EUMGLA", "EUMMAU", "EUMPER", 
             "EUMUND", "EUMHAN", "EUMBON", "MOLTEM", "MOLNEG", "TADTEN", "TADBRA", 
             "TADLOB", "TADVEN", "TADFUL", "TADAEG", "OTOSEC", "OTOPAP", "OTOFOR", 
             "OTOWRO", "OTOMAR", "PRONAS", "PROCEN", "CHETOR", "MORPHR", "MORMIN", 
             "MORDOR", "MORACE", "MORKAL", "MORJUG", "NYCAUR", "NYCMAC", "NYCLAT", 
             "NYCFEM", "MOPCON", "MOPNIA", "MOPSAR", "MOPTRE", "MOPBRA", "MOPDEM", 
             "MOPMOP", "MOPNIV", "MOPSPU", "MOPCON", "MOPMID", "MOPNAN", "MOPPET", 
             "MOPTHE", "SACMIX", "SACFLA", "SACSAC", "SACPEL", "COLSEY", "COLAFR", 
             "DICING", "DICSCU", "DICALB", "DICISA", "RHYNAS", "CORBRE", "EMBDIA", 
             "EMBALE", "EMBBEC", "EMBRAF", "EMBFUR", "EMBSEM", "EMBMON", "BALPLI", 
             "BALIO", "BALINF", "CENMAX", "CYTALE", "PERMAC", "PERLEU", "PERKAP", 
             "CENSEN", "EROSEZ", "EROBOM", "SCLEGA", "UROMAG", "UROBIL", "CHOMIN", 
             "CHOPER", "CHOGOD", "CHITRI", "CHIIMP", "CHIVIL", "CHIDOR", "CHISAL", 
             "PHYSTE", "DIPECA", "CARSUB", "CARPER", "CARBRE", "CARCAS", "VAMPUS", 
             "VAMMEL", "GLOLON", "GLOCOM", "GLOSOR", "GLOLEA", "GLOMOR", "TONBID", 
             "CHOMEX", "LONFER", "LONORI", "LONAUR", "LONMAR", "VAMCAR", "HYLUND", 
             "ECTALB", "LONROB", "LONHAN", "LONBOK", "LONMOR", "LONHES", "LONDEK", 
             "AMECEN", "LIOSPU", "MONPLE", "MONRED", "LICOBS", "PYGBIL", "PLAGEN", 
             "ARTOBS", "ARTTOL", "ARTAZT", "ARTGLA", "ARTHIR", "ARTPHA", "ARTAMP", 
             "ARTCIN", "ARTFIM", "ARTINO", "ARTLIT", "ARTPLA", "ARTJAM", "ARTAND", 
             "ARTCON", "ARTFRA", "ARDNIC", "PHYHAS", "PHYDIS", "PHYELO", "PHYLAT", 
             "MICSCH", "MICMIN", "MICHIR", "MICMEG", "MACWAT", "MACCAL", "DESROT", 
             "TRACIR", "SPHTOX", "PHYPOE", "PHYAPH", "ARIFLA", "MIMBEN", "LEPYER", 
             "LEPCUR", "LEPNIV", "MUSHAR", "STUBID", "STUERY", "STULUI", "STUNAN", 
             "STULIL", "STUMAG", "STUARA", "STUBOG", "STULUD", "STUMOR", "STUTIL", 
             "VAMSPE", "NOCLEP", "NOCALB", "MYSTUB", "MYSROB", "MEGSPA", "LAVFRO", 
             "CARCOR", "CRATHO", "THYLAV", "EMBSER", "CENCEN", "MIMCOZ", "ARTGNO", 
             "ARTWAT", "ENCHAR", "TRINIC", "VAMTHY", "GLYBEH", "GLYSYL", "GLYDAV", 
             "LONINU", "STUMIS", "STUOPO", "CARSOW", "NEOPUS", "LAMBRA", "PHYMAJ", 
             "MICMAT", "MICBRO", "MICSAN", "MORMAG", "MORBLA", "NYCLEP", "NATJAM", 
             "NATMAJ", "NATPRI", "CHITUM", "DYABRO", "EONROB", "NOTNEO", "AETAEQ", 
             "CYNLUZ", "CYNMIN", "PLEANC", "NANVEL", "EPOCRY", "EPOMIN", "DOBAND", 
             "DOBCRE", "PARTEN", "PTETAK", "ROULIN", "BAUDUB", "KERLEN", "NEOZUL", 
             "ARICIR", "ARISOC", "ARICUP", "HISLAE", "HISMAG", "HISHUM", "EPTJAP", 
             "EPTCHI", "EPTAND", "MURHIL", "MURRYU", "SCORUE", "CHANEO", "SCOALB", 
             "FALTAS", "FALMAC", "CISLES", "CISSEA", "GLABEA", "GLAGLE", "GLAMAC", 
             "GLAVAR", "GLAALB", "GLACUR", "GLAHUM", "GLAPOE", "GLAARG", "GLAEGE", 
             "GLAKEN", "GLASUP", "NYCHOW", "NYCNEB", "MINMAN", "MINMAJ", "MINGLE", 
             "MINAFR", "MINMED", "MINSHO", "MINMAC", "VESVUL", "VESPUM", "VESDAR", 
             "VESTRO", "VESFIN", "VESCAU", "VESREG", "VESDOU", "VESBAV", "PHOPAP", 
             "PHOAER", "PHOJAG", "PHOATR", "HYPMUS", "HYPALA", "HYPARA", "HYPCAD", 
             "HYPIMB", "HYPLOP", "HYPPUL", "HYPVOR", "HYPARI", "HYPMAC", "HYPKIT", 
             "MYOGOM", "MYOBUC", "MYOLAN", "MYOANN", "MYOPUN", "MYOANJ", "MYOALC", 
             "MYODAV", "MYOMAC", "MYOOCC", "MYOYAN", "MYOCSO", "MYOHER", "MYOFIM", 
             "RHOHUS", "RHOAEN", "RHOIO", "SCOGRE", "SCOBAL", "SCOSAN", "SCOORI", 
             "NYCCUB", "NYCAEN", "SCODOR", "MOPLEU", "OTOJOH", "OTOMAD", "CHEPAR", 
             "CYNMEX", "CYNPLA", "CYNGRE", "EUMTRU", "TADINS", "TADLAT", "RHICON", 
             "RHIHIL", "RHIHIL", "RHIHIL", "RHIZIA", "RHISIA", "RHIMAE", "RHISHO", 
             "RHIFOR", "RHIMAD", "RHISAK", "RHIRUW", "RHIMON", "RHIBOC", "NYCDAE", 
             "CABAEQ", "LONCON", "MORSTE", "MORHEL", "TADRUS", "TADCON", "TADLEP", 
             "TADENG", "SAHPSE", "MEGVIR", "MEGBRA", "MEGFRA", "QARMOE", "RHIPUM", 
             "RHIHAN", "RHIDEH", "RHIPRI", "RHICSA", "RHIWEN", "RHILEM", "RHIGRI", 
             "RHIDEL", "CUBSIL", "PALPRI", "STEGRA", "CHARAB", "SHAUNE", "MYOBOY", 
             "MYOHEL", "MYOSAN", "MYOGRI", "MYOMAN", "MYOREC", "MYOSAL", "KARSIL", 
             "MIORIS", "MIOFLO", "MINTAO", "MINFOS", "MINAPP", "SUAWHI", "POTBIP", 
             "KHOAEG", "EPTPRA", "EPTKOW", "EPTAUR", "EPTNOC", "EPTMOS", "EPTCAM", 
             "ANZANZ", "ARCANN", "BREMCC", "ASEMAR", "PARROB", "XENHAL", "ICAMEN", 
             "ICAIND", "TANMAN", "ARCBRA", "CECPRI", "PHISPH", "VAMORI", "WITSCH", 
             "WITERE", "DESSTO", "ONYFIN", "AGETOB", "PRIPRA", "HONTSU", "ARCTRA", 
             "TACFRA", "DHOSIG", "PROLEA", "CAMCOM", "SAMMAJ", "TOMRAV", "PIPCOR", 
             "PIPMIN", "PIPSTE", "PIPAER", "PIPEND", "PIPKUH", "PIPPIP", "PIPNAT", 
             "PIPCEY", "PIPMAD", "PIPPER", "PIPNAN", "PIPTEN", "PIPJAV", "PIPRUS", 
             "PIPINE", "PIPSTU", "PIPPAT", "PLEAUR", "PLETAI", "PLETEN", "NYCLEI", 
             "NYCAZO", "NYCNOC", "NYCLAS", "NYCAVI", "NYCMON", "SCOKUH", "SCODIN", 
             "SCOVIR", "SCONIG", "SCOCEL", "SCOROB", "SCOLEU", "SCONUX", "LASCAS", 
             "LASSEM", "LASMIN", "LASBOR", "LASBLO", "COEROB", "HIPLAN", "HIPRUB", 
             "HIPDIN", "HIPMAG", "HIPSPE", "HIPFUL", "HIPOBS", "HIPCOR", "HIPRID", 
             "HIPATE", "HIPDIA", "HIPMAC", "HIPCAL", "HIPFUL", "HIPLAM", "HIPPYG", 
             "HIPARM", "HIPLYL", "HIPCAF", "HIPNEQ", "HIPJON", "HIPPRA", "HIPABA", 
             "HIPCUR", "HIPLEK", "HIPBRE", "HIPCIN", "HIPINE", "HIPPOM", "HIPCRU", 
             "HIPBIC", "HIPDYA", "HIPMEG", "HIPTUR", "HIPCER", "HIPHAL", "HIPPAP", 
             "HIPCOX", "HIPLAR", "HIPBEA", "HIPDOR", "HIPMAR", "HIPGAL", "NYCARG", 
             "NYCHIS", "NYCMAC", "NYCTRA", "NYCGAM", "NYCINT", "NYCMAJ", "NYCTHE", 
             "NYCWOO", "NYCGRA", "NYCJAV", "NYCNAN", "PTEPER", "PTEPAR", "PTEMAC", 
             "PTEDAV", "PTEQUA", "PTEGYM", "MACMIN", "MACSOB", "NYCMAS", "NYCRAB", 
             "NYCVIZ", "NYCAEL", "NYCALB", "NYCCER", "NYCMAJ", "NYCROB", "NYCCYC", 
             "NYCMAL", "NYCCEP", "NYCDRA", "PTENIT", "PTEVAM", "PTEROD", "PTEPSE", 
             "PTEALD", "PTECAN", "PTESCA", "PTETOK", "PTEFUN", "PTENIG", "PTETUB", 
             "PTEPOL", "PTEBRU", "PTEMAH", "PTESAM", "PTEFAU", "PTEHYP", "PTEPOH", 
             "PTEWOO", "PTEMAC", "PTEPIL", "PTEDAS", "PTENEO", "PTEHOW", "PTETON", 
             "PTEPER", "PTEVOE", "PTEADM", "PTEANE", "PTELYL", "PTECON", "PTEMEL", 
             "PTESUB", "PTEGRI", "PTEORN", "PTEVET", "PTEALE", "PTELOM", "PTERAY", 
             "PTEMOL", "PTEMEL", "PTESPE", "PTEOCU", "PTELIV", "PTEPUM", "PTEMAR", 
             "PTECHR", "PTESEY", "ACEMAC", "ACEJUB", "ACECEL", "ACEHUM", "ACELEU", 
             "MYOWHI", "MYODAU", "CHANIG", "CHABEM", "CHAGAL", "CHAJOH", "CHAALO", 
             "CHAJOB", "CHAMAJ", "CHAANS", "CHACHA", "MOLPRE", "MOLMOL", "MOLBON", 
             "MOLSIN", "SACCAN", "SACLEP", "SACBIL", "SACGYM", "MOSNIG", "TAPHAM", 
             "TAPHIL", "TAPLON", "TAPNUD", "TAPTHE", "TAPAUS", "TAPHIL", "TAPMAU", 
             "TAPPER", "TAPGEO", "TAPKAP", "TAPMEL", "RHIMUS", "RHIMIC", "PHYFAL", 
             "MACMAC", "CHRAUR", "STERUF", "MESMAC", "RHIFIS", "RHIALE", "RHIPUM", 
             "BRACAV", "BRANAN", "PLAHEL", "PLAVIT", "PLALIN", "PLABRA", "PLAAUR", 
             "PLAUMB", "PLAINF", "PLADOR", "PLAREC", "MACGIG", "TAPTRO", "SACANT", 
             "LOPSIL", "LOPCAR", "LOPSCH", "LOPBRA", "LOPEVO", "PTEPRI", "HIPDEM", 
             "HIPSOR", "HIPPEL", "HIPINO", "HIPSCU", "HIPORB", "HIPHYP", "HIPGRA", 
             "HIPDUR", "HIPROT", "PTEPEL", "PTETEM", "PTECOG", "PTEUAL", "PTEKEY", 
             "PTEGIL", "PTEARU", "PTEREN", "SCOCOL", "SCOHEA", "SCONUC", "NYCFUR", 
             "PIPABR", "PIPWES", "PIPWAT", "PIPPYG", "PIPPAP", "PIPCOL", "PIPADA", 
             "PLEBAL", "LASEBE", "LASPFE", "LASVAR", "LASATR", "LASDEG", "CHAPLI", 
             "CHAPUM", "CHASOL", "CHABRE", "CHALEU", "CHARUS", "CHABIV", "CHATOM", 
             "MOLAZT", "MOLCUR", "MOLRUF", "MOLCOI", "NYCMAD", "NYCAUR", "RHIHAR", 
             "RHIMAC", "MURGRA", "MURREC", "MURBIC", "HARISO", "PLESAR", "PLEAUS", 
             "PLEKOL", "MYZSCH", "HIPKHA", "HIPBOE", "HIPNIC", "THYDEV", "EUMFLO", 
             "CHAPUS", "PTEPAR", "XERVIE", "ARTROS", "PLAISM", "PLAMAT", "PLAMAS", 
             "PLAALB", "STUSOR", "CARMAN", "LONORC", "LONCHO", "DESDRA", "NATLAN", 
             "NATMEX", "RHIAND", "RHIPET", "RHIPER", "RHIPER", "RHIPUM", "RHIMIN", 
             "PTEFLA", "EPOANS", "STYMIN", "MIRACR", "PTEMED", "MYOPIL", "MYODIE", 
             "MYOPEY", "MYOLON", "MYORUF", "EPTISA", "EPTANA", "PIPMUR", "PIPRAC", 
             "PIPHAN", "SCOTAN", "SCOMAR", "KERMAL", "KERCRY", "KERDEP", "KERTIT", 
             "KERKAC", "KERKRA", "MURHAR", "MINFUL", "MINGRI", "MINSOR", "MINPET", 
             "MINNEW", "BARCAS", "NYCSHE", "PLEOGN", "PLEMAC", "PLESAC", "PLECHR", 
             "HARGRI", "LASFOS", "PLEATA", "PLECRA", "PLERAB", "HIPAGU", "HIPDEC", 
             "HIPCOL", "HIPBOU", "ANOLAT", "ANOCAU", "ANOGEO", "ANOCUL", "ANOLUI", 
             "ANOFIS", "TAPACH", "PERTRI", "TONSAU", "MICMIC", "COEFRI", "HIPMAD", 
             "HIPSUM", "CHIMIC", "LISANG", "NYCKEA", "CYNHOR", "DOBPER", "ROULES", 
             "PTECAP", "NEOGUI", "VESSIN", "NYCPLA", "EPTGOB", "EPTNIL", "SCOHIN", 
             "PIPHES", "PIPANG", "NYCBIF", "MINPAU", "MINNAT", "HYPSAV", "MYOATE", 
             "MYOMOL", "MYOBRA", "MYOBOC", "MYONIP", "CYNABR", "PLASET", "SAUPET", 
             "EUMPAT", "NYCPAR", "RHISIN", "RHIBED", "MYORUF", "PLAINC", "MURWAL", 
             "HIPEIN", "ASEARA", "DIAYOU", "HSUTHO", "UROCON", "RHIPRO", "LONORI", 
             "RHICHI", "MURGUI", "MICGIO", "STUPER", "PLAGUI", "MYOHAN", "MORFRA", 
             "EPOPUS", "NEOMAT", "PARATR", "TYLPYG", "DRYCAP", "LONFOR", "RHIWIL", 
             "RHICOH", "MINEGE", "MINPAL", "MYOSIB", "HIPPEN", "RHIHAD", "SCOLIV", 
             "TRIMEN", "DESMIC", "MURCHR", "PARAUR", "MYOIZE", "OTOLEU", "EUMWIL", 
             "MYOLAV", "CARMON", "LOPKAL", "HIPALO", "CASOPH", "MINMAH", "SCOTRU", 
             "STUPAU", "PERSUB", "THYWYN", "MURSHU", "ANOAEQ", "SCOEJE", "PTERUF", 
             "UROBAK", "MOPBAK", "RHIMIC", "MURLOR", "NYCSHI", "THOSUH", "GLIAQU", 
             "RHISMI", "BARBEI", "GLIBUC", "PARPAU", "NYCSCH", "STUPAR", "RHIHOR", 
             "MYSVEL", "LONPER", "COLKIB", "HSUPAT", "MOLALV", "RHIMAB", "NATMAC", 
             "MURELE", "PLETUR", "PLAFUS", "STUANG", "MURANN", "PLEHOM", "MURFIO", 
             "MYOMID", "HSUCAD", "VAMNYM", "RHISCH", "MINMOS", "PLEKOZ", "TRIPAR", 
             "STUHON", "PARTIA", "CHIMAC", "RHIXIN", "PLESTR", "MURFEA", "RHIKAH", 
             "NEOSOM", "DYARIC", "MYODIM", "EPTTAD", "CHAJOB", "MYOIND", "ANOCAD", 
             "ARTAEQ", "PLEWAR", "RHIMOS", "EUMNAN", "ARTSCH", "STUBAK", "CARBEN", 
             "MYOBAD", "PARFUR", "EPODOB", "MINBRA", "MINGRI", "RHITAT", "STUKOO", 
             "TRIAFE", "RHIBEL", "RHIMCI", "PTERUB", "ASEITA", "HYPLAN", "MINMAG", 
             "RHOMEN", "ANOPER", "MURBEE", "MYOPET", "NYCCOR", "MYOESC", "RHOBIC", 
             "HIPGRI", "ARTBOG", "RHIDAM", "MURPEN", "MICYAT", "STUBUR", "PTECOX", 
             "MYOANN", "MEGAZA", "MYOPHA", "CHAATS", "PTEALL", "THAAUR", "EUMDEL", 
             "MURBAL", "MURHUT", "RHITHA", "URODAV", "MINAEL", "SCOAND", "WALSCA", 
             "RHICYS", "VAMBRO", "PTEMYO", "MURHAR", "CASCAM", "DESLEU", "PARHES", 
             "VAMBID", "NYCMAJ", "DHOTHA", "VESANE", "HYPDOL", "EUDTHO", "EUMCHI", 
             "CHIHER", "TADLAT", "GLOAPO", "MICFOL", "RHIYON", "NOTMAG", "MYSMIO", 
             "ARCREL", "POTMAS", "SUBLAT", "HIPOMA", "HIPFEL", "PHYSIL", "IALAM", 
             "OTOHAR", "HIPKHE", "AUSCLA", "ICASIG", "HASKUM", "MINAMB", "ARCSTO", 
             "THYROB", "PROGUN", "HISDIA", "KIOLOP", "DIZEXS", "PALANT", "NOCLAC", 
             "DESARC", "NOTSUC", "EUMFER", "VAMELI", "MYOLAR", "PLANIT", "SCONIG", 
             "RHIEPI", "RHIACH", "LONINE", "RHIMOR", "VAMMAJ", "SPEAUR", "MURKON", 
             "MYOMIS", "RHINIP", "DIPCEN", "CYNMIL", "KERBRA", "GLOMUT", "MYODIN", 
             "MYOBRO", "MOLMIL", "RHIFRA", "NYCVAR", "RHIREF", "KHOGUN", "PLAANG", 
             "MYOSOW", "VESKAS", "DRAGLI", "RHITRU", "NOCAME", "MINHOR", "GARCRE", 
             "KERBIC", "MYODAR", "HIPGEN", "PHAPHI", "PHABUT", "NECFRA", "SPENAT", 
             "TYLMAL", "PRODAV", "NESWOO", "PTEMES", "PSEPAR", "RHICHA", "PALTUN", 
             "SCOBER", "EPTOGN", "TRAFUL", "PERPAL", "MOLVER", "VAMSIN", "OTORUM", 
             "CORALL", "RHIMAG", "VESAEN", "PTEPEL", "MADLEW", "HIPTEP", "SIMSTO", 
             "CHAPUS", "RHILOB", "KERPUS", "STEBON", "MYOSEC", "VAYPRI", "MURHKA", 
             "VESGRA", "MYOATT", "TYLTON", "RHILUG", "RHILAK", "MIXWEI", "DASGOL", 
             "PIPTAI", "ADAANG", "LAPXIE", "HIPBER", "VESMUR", "STUADR", "PALOLT", 
             "HSUDAS", "MIXDUB", "MIORIV", "RHICOL", "NYCCEL", "XERVIE", "ARTRAV", 
             "CORTET", "HIPAFR", "VESLAP", "MACKOP", "EUMCHI", "CASYOK", "RIVWIL", 
             "MYOSOR", "AEGKNI", "PALQUE", "LONMAN", "VESANT", "HIPMOR", "MYOBEL", 
             "ARCPRA", "PSESCH", "TYLERE", "PIPMON", "GARKOE", "VESSPE", "NECADI", 
             "VESOED", "MYOMYS", "MINSCH", "PTEALI", "EPTCHA", "MYOCRY", "MYOZEN", 
             "KOOPAL", "BARDAR", "MYOANC", "MYOLEP", "EPTULA", "ANAINS", "PHORAP", 
             "BARPAC", "STELAN", "HYPPET", "DOREDW", "DORSTE", "RHIRHO", "LAEKIR", 
             "MURJAI", "DASEGA", "ASEDON", "EMBSEN", "EPTPAC", "RHICOG", "LICDEG", 
             "NANMAC", "MINNIM", "HIPKHA", "CHISCO", "MICBUR", "HIPARP", "HIPMAC", 
             "RHIHIP", "SCOALT", "RHOVEL", "LASBLO", "MYOBOR", "LYRLYR", "RHIGOR", 
             "DORCYC", "RHIVUL", "NANINT", "RHIDEC", "HIPGRI", "MICSIM", "BALINF", 
             "RHIGEO", "OZILOR", "NANARG", "DASINS", "RHIMUR", "DORWOL", "MACGIG", 
             "ANOJAV", "RHIIND", "RHISPE", "AUSAUS", "RHIDOB", "RHILUC", "BALSEI", 
             "GARKEE", "DORSEM", "MYOFED", "STUGIA", "PTEPYR", "MYONIM", "PSENYA", 
             "HIPKUN", "RHIBEM", "HIPCER", "HYPAFF", "NANTHE", "CHIGOR", "MACCOM", 
             "MYONYC", "NYCHIS", "RHILUE", "RHIETJ", "RHICOM", "EMBBEC", "RHIBRO", 
             "DORMUS", "MURPLU", "RHIDIA", "RHIMON", "MACVIT", "TONBAK", "RHINAN", 
             "HARESP", "HIPIPP", "TONMAR", "RHIALT", "RHIINS", "ASEMAJ", "OZIPET", 
             "DORCAM", "RHIAXI", "MICTRE", "ANTOMA", "RHIODA", "RHIFER", "MICNOR", 
             "RHILAN", "MACTHO", "KERFUR", "MACCRY", "RHYNAS", "GLAATR", "PLEGAI", 
             "DORCOR", "LASARE", "PSEKIT", "AUSKUB", "CYNMAS", "AEOVIL", "PLAAQU", 
             "COLGAL", "PALTUP", "NYCGRA", "DASXAN", "NESFAR", "MURJIN", "AEOEGR", 
             "PTEENN", "NYCWRI", "MYOPIL", "VAMVOR", "CARLEA", "MIRJOF", "NYCBEL", 
             "SCOLIB", "PTEWET", "MYOBAR", "HIPCON", "QUIFRI", "BONMEN", "MYOWEB", 
             "HANAGA", "MYOCLY", "LAESTA", "MYOTSC", "MYOBAK", "AEOCIN", "SUBMOU", 
             "MOPTUR", "DASINT", "PTEPUS", "THATOR", "MEGALB", "MYOALT", "PSEROS", 
             "PTEMEX", "VESPRA", "PIPSIM", "PTEFUL", "LAEMAT", "PIPDHO", "TYLFUL", 
             "WITSIG", "SCOCOL", "LAEMAL", "NYCHAP", "MYOCAU", "CHITUM", "NYCMAC", 
             "MYOBAR", "MYOHYR", "MOPKER", "AFRHEL", "PSETEN", "TURHAR", "NYCCRA", 
             "NYCSER", "PTEPSI", "MURFAN", "RHOPER", "NYCEIS", "LAECAP", "LASEGA", 
             "TAPINC", "MURLIB", "PTEFUS", "NEOANC", "LAEROB", "EPOINT", "SCOOLD", 
             "ROUPAT", "MURRON", "LOPOCC", "SACKEN", "PSEISA", "GLOVAL", "RHICON", 
             "PALSPI", "PSEREN", "VESSYL", "NYCHOL", "PSEBRU", "MACHAN", "AFRNAN", 
             "LASFRA", "SUBCAL", "SCOOCC", "HYPMOR", "MYZAFR", "PIPCRE", "VESMAJ", 
             "AEOSEM", "PHISEV", "HIPMIN", "MEGLOP", "PTEPOR", "MYOHOV", "NEOBEM", 
             "VANRUE", "GLOANT", "KERDON", "MYOARM", "CHAPIC", "CASDIM", "OZIRID", 
             "STEQUE", "MOLFEN", "OZIPLA", "MINORI", "OZIBEC", "MINARE", "MINWIL", 
             "CYNFRE", "MOLFLU", "CYNKUI", "OZIKIT", "OZILUM", "MOPLEU", "MINBLE", 
             "MOLNIG", "MOLMEL", "OZICOB", "MINVIL", "CYNTON", "OZIHAL", "SETELE", 
             "MINESC")), row.names = c(NA, -1700L), class = "data.frame")

}
