species_table <-
function(x){
  
structure(list(abbreviation = c("BARBAR", "EPTISA", "EPTNIL", 
                                "EPTSER", "HYPSAV", "MINSCH", "MYOALC", "MYOBEC", "MYOBRA", "MYOCAP", 
                                "MYODAS", "MYODAU", "MYOEMA", "MYOESC", "MYOMYO", "MYOMYS", "MYONAT", 
                                "NYCLAS", "NYCLEI", "NYCNOC", "PIPKUH", "PIPNAT", "PIPPIP", "PIPPYG", 
                                "PLEAUR", "PLEAUS", "RHIEUR", "RHIFER", "RHIHIP", "TADTEN", "VESMUR", 
                                "ANTPAL", "CORTOW", "EPTFUS", "EUDMAC", "EUMFLO", "EUMPER", "EUMUND", 
                                "LASBLO", "LASBOR", "LASCIN", "LASEGA", "LASINT", "LASNOC", "LASSEM", 
                                "LASXAN", "MACCAL", "MOLMOL", "MORMEG", "MYOAUS", "MYOCAL", "MYOCIL", 
                                "MYOEVO", "MYOGRI", "MYOLEI", "MYOLUC", "MYOOCC", "MYOSEP", "MYOSOD", 
                                "MYOTHY", "MYOVEL", "MYOVOL", "MYOYUM", "NYCFEM", "NYCHUM", "NYCMAC", 
                                "PARHES", "PERSUB", "TADBRA", "CHAPUM", "EPTHOT", "LAEBOT", "LAEWIN", 
                                "MINNAT", "MYOBOC", "NEOCAP", "RHIBLA", "RHICLI", "RHIDEN", "RHIFUM", 
                                "RHIHIL", "RHILAN", "RHISIM", "RHISMI", "RHISWI", "SAUPET", "SCODIN", 
                                "SCONIG", "TADAEG", "BALIO", "BALPLI", "BAUDUB", "CENCEN", "CENMAX", 
                                "CORTOW", "CYNMEX", "DICALB", "EPTBRA", "EPTFUR", "EPTFUS", "EUDMAC", 
                                "EUMGLA", "EUMPER", "LASBLO", "LASCIN", "LASINS", "LASINT", "LASSEM", 
                                "LASXAN", "MACCAL", "MOLMOL", "MOLRUF", "MOLSIN", "MOLTEM", "MORBLA", 
                                "MYOELE", "MYOKEA", "MYONIG", "MYORIP", "NOCLEP", "NYCHUM", "NYCLAT", 
                                "NYCMAC", "PARHES", "PERKAP", "PERMAC", "PROCEN", "PTEDAV", "PTEGYM", 
                                "PTEMAC", "PTEPAR", "PTEPER", "PTEQUA", "RHOAEN", "RHYNAS", "SACBIL", 
                                "SACLEP", "TADBRA"), 
               latin_name = c("Barbastella barbastellus", 
                              "Eptesicus isabellinus", "Eptesicus nilssonii", "Eptesicus serotinus", 
                              "Hypsugo savii", "Miniopterus schreibersii", "Myotis alcathoe", 
                              "Myotis bechsteinii", "Myotis brandtii", "Myotis capaccinii", 
                              "Myotis dasycneme", "Myotis daubentonii", "Myotis emarginatus", 
                              "Myotis escalerai", "Myotis myotis", "Myotis mystacinus", "Myotis nattereri", 
                              "Nyctalus lasiopterus", "Nyctalus leisleri", "Nyctalus noctula", 
                              "Pipistrellus kuhlii", "Pipistrellus nathusii", "Pipistrellus pipistrellus", 
                              "Pipistrellus pygmaeus", "Plecotus auritus", "Plecotus austriacus", 
                              "Rhinolophus euryale", "Rhinolophus ferrumequinum", "Rhinolophus hipposideros", 
                              "Tadarida teniotis", "Vespertilio murinus", "Antrozous pallidus", 
                              "Corynorhinus townsendii", "Eptesicus fuscus", "Euderma maculatum", 
                              "Eumops floridanus", "Eumops perotis", "Eumops underwoodi", "Lasiurus blossevillii", 
                              "Lasiurus borealis", "Lasiurus cinereus", "Lasiurus ega", "Lasiurus intermedius", 
                              "Lasionycteris noctivagans", "Lasiurus seminolus", "Lasiurus xanthinus", 
                              "Macrotus californicus", "Molossus molossus", "Mormoops megalophylla", 
                              "Myotis austroriparius", "Myotis californicus", "Myotis ciliolabrum", 
                              "Myotis evotis", "Myotis grisescens", "Myotis leibii", "Myotis lucifugus", 
                              "Myotis occultus", "Myotis septentrionalis", "Myotis sodalis", 
                              "Myotis thysanodes", "Myotis velifer", "Myotis volans", "Myotis yumanensis", 
                              "Nyctinomops femorosaccus", "Nycticeius humeralis", "Nyctinomops macrotis", 
                              "Parastrellus hesperus", "Perimyotis subflavus", "Tadarida brasiliensis", 
                              "Chaerophon pumilus", "Eptesicus hottentotus", "Laephotis botswanae", 
                              "Laephotis wintoni", "Miniopterus natalensis", "Myotis bocagei", 
                              "Neoromicia capensis", "Rhinolophus blasii", "Rhinolophus clivosis", 
                              "Rhinolophus denti", "Rhinolophus fumigatus", "Rhinolophus hildebrandtii", 
                              "Rhinolophus landeri", "Rhinolophus simulator", "Rhinolophus smithersi", 
                              "Rhinolophus swinnyi", "Sauromys petrophilus", "Scotophilus dinganii", 
                              "Scotophilus Nigrita", "Tadarida aegyptiaca", "Balantiopteryx io", 
                              "Balantiopteryx plicata", "Bauerus dubiaquercus", "Centronycteris centralis", 
                              "Centronycteris maximiliani", "Corynorhinus townsendii", "Cynomops mexicanus", 
                              "Diclidurus albus", "Eptesicus brasiliensis", "Eptesicus furinalis", 
                              "Eptesicus fuscus", "Euderma maculatum", "Eumops glaucinus", 
                              "Eumops perotis", "Lasiurus blossevillii", "Lasiurus cinereus", 
                              "Lasiurus insularis", "Lasiurus intermedius", "Lasiurus seminolus", 
                              "Lasiurus xanthinus", "Macrotus californicus", "Molossus molossus", 
                              "Molossus rufus", "Molossus sinaloae", "Molossops temminckii", 
                              "Mormoops blainvillei", "Myotis elegans", "Myotis keaysi", "Myotis nigricans", 
                              "Myotis riparius", "Noctilio leporinus", "Nycticeius humeralis", 
                              "Nyctinomops laticaudatus", "Nyctinomops macrotis", "Parastrellus hesperus", 
                              "Peropteryx kappleri", "Peropteryx macrotis", "Promops centralis", 
                              "Pteronotus davyi", "Pteronotus gymnonotus", "Pteronotus macleayii", 
                              "Pteronotus parnellii", "Pteronotus personatus", "Pteronotus quadridens", 
                              "Rhogeessa aeneus", "Rhynchonycteris naso", "Saccopteryx bilineata", 
                              "Saccopteryx leptura", "Tadarida brasiliensis"), 
               english_name = c("Western barbastelle", 
                                "Meridional serotine", "Northern bat", "Common serotine", "Savi's pipistrelle", 
                                "Common bent-wing bat", "Alcathoe myotis", "Bechstein's myotis", 
                                "Brandt's myotis", "Long-fingered bat", "Pond myotis", "Daubenton's myotis", 
                                "Geoffroy's myotis", "Escalera's bat", "Mouse-eared myotis", 
                                "Whiskered myotis", "Natterer's myotis", "Giant noctule", "Lesser noctule", 
                                "Noctule", "Kuhl's pipistrelle", "Nathusius' pipistrelle", "Common pipistrelle", 
                                "Soprano pipistrelle", "Brown long-eared bat", "Grey long-eared bat", 
                                "Mediterranean horseshoe bat", "Greater horseshoe bat", "Lesser horseshoe bat", 
                                "European free-tailed bat", "Particoloured bat", "Pallid bat", 
                                "Townsend's big-eared bat", "Big brown bat", "Spotted bat", "Florida bonneted bat", 
                                "Greater bonneted bat", "Underwood's bonneted", "Western red bat", 
                                "Eastern red bat", "Hoary bat", "Southern yellow", "Northern yellow bat", 
                                "Silver-haired bat", "Seminole bat", "Western yellow bat", "California leaf-nosed bat", 
                                "Pallas's mastiff bat", "Ghost-faced", "Southeastern myotis", 
                                "California myotis", "Western Small-footed myotis", "Long-eared myotis", 
                                "Gray myotis", "Eastern small-footed myotis", "Little brown myotis", 
                                "Arizona myotis", "Northern myotis", "Indiana myotis", "Fringed myotis", 
                                "Cave myotis", "Long-legged myotis", "Yuma myotis", "Pocketed free-tail", 
                                "Evening bat", "Big free-tailed bat", "Canyon bat", "Tricolored bat", 
                                "Mexican free-tailed bat", "Little free-tailed", "Long-tailed house", 
                                "Botswanan long-eared", "De Winton's long-eared", "Natal long-fingered", 
                                "Rufous mouse-eared", "Cape serotine", "Blasius's horseshoe", 
                                "Geoffroy's horseshoe", "Dent's horseshoe", "Ruppell's horseshoe", 
                                "Hildebrandt's horseshoe", "Lander's horseshoe", "Bushveld horseshoe", 
                                "Smithers's horseshoe", "Swinny's horseshoe", "Roberts's flat-headed", 
                                "African yellow", "Schreber's yellow", "Egyptian free-tailed", 
                                "Thomas's sac-winged", "Gray sac-winged", "Van Gelder's", "Thomas's shaggy", 
                                "Shaggy", "Townsend's big-eared", "Mexican dog-faced", "Northern ghost", 
                                "Brazilian brown", "Argentine brown", "Big brown", "Spotted", 
                                "Eumops floridanus", "Western Mastiff", "Desert red", "Hoary", 
                                "Cuban Yellow", "Northern yellow", "Seminole", "Western Bat", 
                                "California leaf-nosed", "Velvety free-tailed", "Black mastiff", 
                                "Sinaloan mastiff", "Dwarf dog-faced", "Antillean ghost-faced", 
                                "Elegant myotis", "Hairy-legged myotis", "Black myotis", "Riparian myotis", 
                                "Greater bulldog", "Evening Bat", "Broad-eared", "Big free-tailed", 
                                "Western pipistrelle", "Greater dog-like", "Lesser dog-like", 
                                "Promops Centralis", "Davy's naked-backed", "Big naked-backed", 
                                "Macleay's mustached", "Parnell's mustached", "Wagner's mustached", 
                                "Sooty mustached", "Yucatan yellow", "Proboscis", "Greater sac-winged", 
                                "Lesser sac-winged", "Mexican free-tailed")),
          row.names = c(NA,-138L),
          class = c("tbl_df", "tbl", "data.frame"))

}
