species_table <-
function(x){
  
  structure(list(abbreviation = c("ANTPAL", "BALIO", "BALPLI", 
                                  "BARBAR", "BAUDUB", "CENCEN", "CENMAX", "CHAPUM", "CORTOW", "CYNMEX", 
                                  "DICALB", "EPTANA", "EPTBOT", "EPTBRA", "EPTFUR", "EPTFUS", "EPTHOT", 
                                  "EPTISA", "EPTNIL", "EPTSER", "EUDMAC", "EUMFLO", "EUMGLA", "EUMPER", 
                                  "EUMUND", "HYPSAV", "LAEBOT", "LAEWIN", "LASNOC", "LASBLO", "LASBOR", 
                                  "LASCIN", "LASEGA", "LASINS", "LASINT", "LASSEM", "LASXAN", "MACCAL", 
                                  "MINNAT", "MINSCH", "MOLTEM", "MOLMOL", "MOLRUF", "MOLSIN", "MORBLA", 
                                  "MORMEG", "MYOALC", "MYOAUR", "MYOAUS", "MYOBEC", "MYOBLY", "MYOBOC", 
                                  "MYOBRA", "MYOCAL", "MYOCAP", "MYOCIL", "MYOCRY", "MYODAS", "MYODAU", 
                                  "MYODAV", "MYOELE", "MYOEMA", "MYOESC", "MYOEVO", "MYOGRI", "MYOKEA", 
                                  "MYOLEI", "MYOLUC", "MYOMYO", "MYOMYS", "MYONAT", "MYONIG", "MYOOCC", 
                                  "MYOPUN", "MYORIP", "MYOSEP", "MYOSOD", "MYOTHY", "MYOVEL", "MYOVOL", 
                                  "MYOYUM", "NEOCAP", "NOCLEP", "NYCAZO", "NYCLAS", "NYCLEI", "NYCNOC", 
                                  "NYCHUM", "NYCFEM", "NYCLAT", "NYCMAC", "PARHES", "PERSUB", "PERKAP", 
                                  "PERMAC", "PIPHAN", "PIPHES", "PIPKUH", "PIPMAD", "PIPNAT", "PIPPIP", 
                                  "PIPPYG", "PLEAUR", "PLEAUS", "PLEGAI", "PLEKOL", "PLEMAC", "PLESAR", 
                                  "PLETEN", "PROCEN", "PTEDAV", "PTEGYM", "PTEMAC", "PTEPAR", "PTEPER", 
                                  "PTEQUA", "RHIBLA", "RHICLI", "RHIDEN", "RHIEUR", "RHIFER", "RHIFUM", 
                                  "RHIHIL", "RHIHIP", "RHILAN", "RHIMEH", "RHISIM", "RHISMI", "RHISWI", 
                                  "RHOAEN", "RHYNAS", "SACBIL", "SACLEP", "SAUPET", "SCODIN", "SCONIG", 
                                  "TADAEG", "TADBRA", "TADTEN", "VESMUR"), 
                 latin_name = c("Antrozous pallidus", 
                                "Balantiopteryx io", "Balantiopteryx plicata", "Barbastella barbastellus", 
                                "Bauerus dubiaquercus", "Centronycteris centralis", "Centronycteris maximiliani", 
                                "Chaerophon pumilus", "Corynorhinus townsendii", "Cynomops mexicanus", 
                                "Diclidurus albus", "Eptesicus anatolicus", "Eptesicus bottae", 
                                "Eptesicus brasiliensis", "Eptesicus furinalis", "Eptesicus fuscus", 
                                "Eptesicus hottentotus", "Eptesicus isabellinus", "Eptesicus nilssonii", 
                                "Eptesicus serotinus", "Euderma maculatum", "Eumops floridanus", 
                                "Eumops glaucinus", "Eumops perotis", "Eumops underwoodi", "Hypsugo savii", 
                                "Laephotis botswanae", "Laephotis wintoni", "Lasionycteris noctivagans", 
                                "Lasiurus blossevillii", "Lasiurus borealis", "Lasiurus cinereus", 
                                "Lasiurus ega", "Lasiurus insularis", "Lasiurus intermedius", 
                                "Lasiurus seminolus", "Lasiurus xanthinus", "Macrotus californicus", 
                                "Miniopterus natalensis", "Miniopterus schreibersii", "Molossops temminckii", 
                                "Molossus molossus", "Molossus rufus", "Molossus sinaloae", "Mormoops blainvillei", 
                                "Mormoops megalophylla", "Myotis alcathoe", "Myotis aurascens", 
                                "Myotis austroriparius", "Myotis bechsteinii", "Myotis blythii", 
                                "Myotis bocagei", "Myotis brandtii", "Myotis californicus", "Myotis capaccinii", 
                                "Myotis ciliolabrum", "Myotis crypticus", "Myotis dasycneme", 
                                "Myotis daubentonii", "Myotis davidii", "Myotis elegans", "Myotis emarginatus", 
                                "Myotis escalerai", "Myotis evotis", "Myotis grisescens", "Myotis keaysi", 
                                "Myotis leibii", "Myotis lucifugus", "Myotis myotis", "Myotis mystacinus", 
                                "Myotis nattereri", "Myotis nigricans", "Myotis occultus", "Myotis punicus", 
                                "Myotis riparius", "Myotis septentrionalis", "Myotis sodalis", 
                                "Myotis thysanodes", "Myotis velifer", "Myotis volans", "Myotis yumanensis", 
                                "Neoromicia capensis", "Noctilio leporinus", "Nyctalus azoreum", 
                                "Nyctalus lasiopterus", "Nyctalus leisleri", "Nyctalus noctula", 
                                "Nycticeius humeralis", "Nyctinomops femorosaccus", "Nyctinomops laticaudatus", 
                                "Nyctinomops macrotis", "Parastrellus hesperus", "Perimyotis subflavus", 
                                "Peropteryx kappleri", "Peropteryx macrotis", "Pipistrellus hanaki", 
                                "Pipistrellus hesperidus", "Pipistrellus kuhlii", "Pipistrellus maderensis", 
                                "Pipistrellus nathusii", "Pipistrellus pipistrellus", "Pipistrellus pygmaeus", 
                                "Plecotus auritus", "Plecotus austriacus", "Plecotus gaisleri", 
                                "Plecotus kolombatovici", "Plecotus macrobullaris", "Plecotus sardus", 
                                "Plecotus teneriffae", "Promops centralis", "Pteronotus davyi", 
                                "Pteronotus gymnonotus", "Pteronotus macleayii", "Pteronotus parnellii", 
                                "Pteronotus personatus", "Pteronotus quadridens", "Rhinolophus blasii", 
                                "Rhinolophus clivosis", "Rhinolophus denti", "Rhinolophus euryale", 
                                "Rhinolophus ferrumequinum", "Rhinolophus fumigatus", "Rhinolophus hildebrandtii", 
                                "Rhinolophus hipposideros", "Rhinolophus landeri", "Rhinolophus mehelyi", 
                                "Rhinolophus simulator", "Rhinolophus smithersi", "Rhinolophus swinnyi", 
                                "Rhogeessa aeneus", "Rhynchonycteris naso", "Saccopteryx bilineata", 
                                "Saccopteryx leptura", "Sauromys petrophilus", "Scotophilus dinganii", 
                                "Scotophilus Nigrita", "Tadarida aegyptiaca", "Tadarida brasiliensis", 
                                "Tadarida teniotis", "Vespertilio murinus"), 
                 common_name = c("Pallid bat", 
                                 "Thomas's sac-winged", "Gray sac-winged", "Western barbastelle", 
                                 "Van Gelder's", "Thomas's shaggy", "Shaggy", "Little free-tailed", 
                                 "Townsend's big-eared", "Mexican dog-faced", "Northern ghost", 
                                 "Anatolian serotine", "Botta's serotine", "Brazilian brown", 
                                 "Argentine brown", "Big brown", "Long-tailed house", "Meridional serotine", 
                                 "Northern", "Common serotine", "Spotted", "Florida bonneted", 
                                 "Wagner's bonneted", "Western Mastiff", "Underwood's bonneted", 
                                 "Savi's pipistrelle", "Botswanan long-eared", "De Winton's long-eared", 
                                 "Silver-haired", "Desert red", "Eastern red", "Hoary", "Southern yellow", 
                                 "Cuban Yellow", "Northern yellow", "Seminole", "Western yellow", 
                                 "California leaf-nosed", "Natal long-fingered", "Common bent-wing", 
                                 "Dwarf dog-faced", "Velvety free-tailed", "Black mastiff", "Sinaloan mastiff", 
                                 "Antillean ghost-faced", "Ghost-faced", "Alcathoe", "Steppe whskered", 
                                 "Southeastern myotis", "Bechstein's", "Lesser mouse-eared", "Rufous mouse-eared", 
                                 "Brandt's", "California myotis", "Long-fingered bat", "Western Small-footed myotis", 
                                 "Cryptic myotis", "Pond", "Daubenton's", "David's myotis", "Elegant myotis", 
                                 "Geoffroy's", "Escalera's", "Long-eared myotis", "Gray myotis", 
                                 "Hairy-legged myotis", "Eastern small-footed myotis", "Little brown myotis", 
                                 "Greater mouse-eared", "Whiskered", "Natterer's", "Black myotis", 
                                 "Arizona myotis", "Felten's myotis", "Riparian myotis", "Northern myotis", 
                                 "Indiana myotis", "Fringed myotis", "Cave myotis", "Long-legged myotis", 
                                 "Yuma myotis", "Cape serotine", "Greater bulldog", "Azores noctule", 
                                 "Greater noctule", "Leisler's", "Common noctule", "Evening", 
                                 "Pocketed free-tail", "Broad-eared", "Big free-tailed", "Western pipistrelle", 
                                 "Tricolored bat", "Greater dog-like", "Lesser dog-like", "Hanaki's dwarf", 
                                 "Dusky pipistrelle", "Kuhl's pipistrelle", "Maderia pipistrelle", 
                                 "Nathusius' pipistrelle", "Common pipistrelle", "Soprano pipistrelle", 
                                 "Brown long-eared", "Grey long-eared", "Gaisler's long-eared", 
                                 "Kolombatovic's long-eared", "Alpine long-eared", "Sardinian long-eared", 
                                 "Canary big-eared", "Promops Centralis", "Davy's naked-backed", 
                                 "Big naked-backed", "Macleay's mustached", "Parnell's mustached", 
                                 "Wagner's mustached", "Sooty mustached", "Blasius's horseshoe", 
                                 "Geoffroy's horseshoe", "Dent's horseshoe", "Mediterranean horseshoe", 
                                 "Greater horseshoe", "Ruppell's horseshoe", "Hildebrandt's horseshoe", 
                                 "Lesser horseshoe", "Lander's horseshoe", "Mehely's horseshoe", 
                                 "Bushveld horseshoe", "Smithers's horseshoe", "Swinny's horseshoe", 
                                 "Yucatan yellow", "Proboscis", "Greater sac-winged", "Lesser sac-winged", 
                                 "Roberts's flat-headed", "African yellow", "Schreber's yellow", 
                                 "Egyptian free-tailed", "Mexican free-tailed", "European free-tailed", 
                                 "Parti-coloured")), 
            row.names = c(NA, -140L),
            class = c("tbl_df", 
                      "tbl", "data.frame")
            )
}
